const $ = (s, r = document) => r.querySelector(s);

const NAV = [
  ['/', 'Início'],
  ['/organizar', 'Organizar'],
  ['/estudar', 'Estudar'],
  ['/bem-estar', 'Bem-estar'],
  ['/instituicao', 'Instituição']
];

const seed = {
  user: {name:'Ana Silva',email:'ana@universidadebloom.edu.br',course:'Ciência da Computação',className:'4º semestre · Turma B',institution:'Universidade Bloom',avatar:'AS'},
  tasks:[
    {id:1,title:'Estudar Banco de Dados',cat:'Estudos',due:'Hoje',priority:'Alta',done:false},
    {id:2,title:'Revisar introdução do TCC',cat:'TCC',due:'Amanhã',priority:'Média',done:false},
    {id:3,title:'Enviar relatório do grupo',cat:'Projeto',due:'Hoje',priority:'Alta',done:true}
  ],
  habits:[
    {id:1,title:'Beber água',goal:'2 L por dia',freq:'Diário',progress:70,checked:false},
    {id:2,title:'Dormir bem',goal:'8h por noite',freq:'Diário',progress:86,checked:false},
    {id:3,title:'Movimentar o corpo',goal:'30 min',freq:'5x por semana',progress:58,checked:false},
    {id:4,title:'Estudar com foco',goal:'2 sessões',freq:'Diário',progress:75,checked:false}
  ],
  ideas:[
    {id:1,text:'Pesquisar referências para o TCC',kind:'Pensamento',archived:false},
    {id:2,text:'Testar sons de floresta no modo foco',kind:'Ideia',archived:false}
  ],
  diary:[
    {id:1,title:'Um dia mais leve',date:'Hoje',mood:'🙂',text:'Consegui organizar minha tarde e fiz uma pausa antes da reunião.'},
    {id:2,title:'Reflexão',date:'Ontem',mood:'😌',text:'Percebi que estudar em blocos menores me ajuda a começar.'}
  ],
  checkins:[
    {id:1,date:'Hoje',mood:'🙂',factors:['Estudos'],note:'Dia organizado até aqui.'},
    {id:2,date:'Ontem',mood:'😐',factors:['Sono'],note:'Preciso desacelerar no fim do dia.'}
  ],
  notifications:[
    {id:1,icon:'📚',title:'Seu foco de hoje está esperando por você.',time:'Hoje, 08:42',kind:'Estudo',read:false},
    {id:2,icon:'🗓️',title:'Você tem 3 compromissos hoje.',time:'Hoje, 07:55',kind:'Agenda',read:false},
    {id:3,icon:'🌿',title:'Que tal fazer seu check-in emocional?',time:'Ontem, 20:10',kind:'Bem-estar',read:true},
    {id:4,icon:'🏫',title:'Novo evento disponível na instituição.',time:'Ontem, 16:20',kind:'Instituição',read:true}
  ],
  events:[
    {id:1,date:'14/09',title:'Workshop de Projetos',where:'Auditório principal',type:'Instituição',details:'Encontro sobre projetos acadêmicos e oportunidades.',joined:false,reminder:false},
    {id:2,date:'16/09',title:'Grupo de estudos — Banco de Dados',where:'Biblioteca',type:'Acadêmico',details:'Revisão colaborativa para a próxima avaliação.',joined:true,reminder:true},
    {id:3,date:'20/09',title:'Campanha Semana do Bem-estar',where:'Espaço de convivência',type:'Bem-estar',details:'Atividades opcionais de cuidado e integração.',joined:false,reminder:false}
  ],
  supportServices:[
    {id:1,name:'CAPS / Atendimento municipal',distance:'2,8 km',category:'Atendimento em saúde mental',address:'Rua das Flores, 120 · Centro',rating:'4,8',hours:'Seg–Sex · 08:00–18:00',phone:'(11) 4000-0101'},
    {id:2,name:'Centro de acolhimento estudantil',distance:'4,1 km',category:'Apoio psicológico e orientação',address:'Av. da Universidade, 450',rating:'4,9',hours:'Seg–Sex · 09:00–19:00',phone:'(11) 4000-0202'},
    {id:3,name:'Clínica-escola universitária',distance:'7,4 km',category:'Atendimento acadêmico',address:'Rua do Campus, 75',rating:'4,7',hours:'Seg–Sáb · 08:00–16:00',phone:'(11) 4000-0303'}
  ],
  communities:[
    {id:1,name:'Programação',icon:'💻',desc:'Grupo de estudo para programação web',members:18,joined:true,posts:[{author:'Rafa',text:'Alguém quer revisar React hoje?',time:'08:20',likes:4,comments:2}]},
    {id:2,name:'Vestibular',icon:'🎓',desc:'Dicas e apoio para provas',members:34,joined:false,posts:[]},
    {id:3,name:'Hobbies criativos',icon:'🎨',desc:'Trocas sobre desenho, música e projetos',members:12,joined:false,posts:[]},
    {id:4,name:'Banco de Dados',icon:'📚',desc:'Revisões para avaliações',members:26,joined:false,posts:[]},
    {id:5,name:'Dificuldades acadêmicas',icon:'🗣️',desc:'Espaço para conversar e compartilhar estratégias',members:21,joined:false,posts:[]},
    {id:6,name:'Bem-estar',icon:'🌱',desc:'Pausas e hábitos saudáveis',members:16,joined:false,posts:[]}
  ],
  supportRequests:[{id:1,date:'27/08',type:'Orientação',person:'Setor de acolhimento',status:'Em análise',summary:'Gostaria de conversar sobre organização e sobrecarga acadêmica.'}],
  reports:[{id:1,code:'DEN-2026-001',date:'25/08',title:'Situação no ambiente escolar',anonymous:true,status:'Em análise'}],
  feedback:[{id:1,date:'22/08',type:'Sugestão',target:'Carga de atividades',status:'Recebido'}],
  communications:[
    {id:1,type:'Comunicado',title:'Novo período de inscrições para monitoria',body:'As inscrições estão abertas até sexta-feira.',date:'Hoje'},
    {id:2,type:'Campanha',title:'Semana do Bem-estar',body:'Atividades opcionais de cuidado, pausa e convivência.',date:'Ontem'},
    {id:3,type:'Conteúdo',title:'Biblioteca com horários especiais',body:'Consulte os novos horários durante o período de avaliações.',date:'20/08'}
  ]
};

const state = {
  data: JSON.parse(localStorage.getItem('bloom-data') || 'null') || seed,
  mood:null,
  sound:'rain',
  route:'/',
  timer:{seconds:1500,running:false,mode:'25/5',interval:null},
  settings:Object.assign({reminders:true,study:true,wellbeing:true,institution:true,theme:'light',homeRecommendations:true},JSON.parse(localStorage.getItem('bloom-settings')||'{}')),
  toastTimer:null
};

document.documentElement.dataset.theme=state.settings.theme;

function save(){localStorage.setItem('bloom-data',JSON.stringify(state.data));localStorage.setItem('bloom-settings',JSON.stringify(state.settings));}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function route(){return decodeURIComponent(location.hash.replace(/^#/,'')||'/')||'/';}
function go(path){location.hash=path;}
function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove('show'),2300);}
function shell(c){return `<div class="container">${c}</div>`;}
function pageHead(k,t,d,a=''){return `<div class="page-head"><div><div class="kicker">${k}</div><h1>${t}</h1><p>${d}</p></div><div class="head-actions">${a}</div></div>`;}
function btn(label,cls='secondary',action=''){return `<button class="btn ${cls}" ${action?`onclick="${action}"`:''}>${label}</button>`;}
function linkBtn(label,path,cls='secondary'){return `<a class="btn ${cls}" href="#${path}">${label}</a>`;}
function tabs(items,current,handler){return `<div class="tabs">${items.map(x=>`<button class="tab ${current===x?'active':''}" onclick="${handler}('${x}')">${x}</button>`).join('')}</div>`;}
function cardTitle(t,d=''){return `<div class="card-title"><div><h2>${t}</h2>${d?`<div class="sub">${d}</div>`:''}</div></div>`;}
function card(t,d,b,c=''){return `<section class="card ${c}">${cardTitle(t,d)}${b}</section>`;}

function home(){
  const c=state.data.checkins[0];
  const recommendation=(c?.mood==='😔'||c?.mood==='😣')
    ? ['Um cuidado para agora','Seu dia parece mais pesado. Uma pausa curta antes da próxima tarefa pode ajudar.','Fazer uma pausa','/bem-estar/praticas']
    : ['Uma sugestão para hoje','Comece por uma tarefa pequena. Depois, escolha se quer continuar ou pausar.','Organizar meu dia','/organizar'];
  return shell(pageHead('Seu espaço de cuidado','Bom dia, Ana!','Vamos cuidar de você hoje?')+
    `<div class="home-grid">${card('Como você está hoje','Um check-in rápido para perceber seu momento.',`<div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(([i,t])=>`<button class="mood ${c?.mood===i?'selected':''}" onclick="state.mood='${i}';render()"><span>${i}</span>${t}</button>`).join('')}</div><div class="head-actions">${btn('Fazer check-in','primary','saveMood()')}${btn('Ver histórico','secondary','openMoodHistory()')}</div>`,'main-card')+
    card('Momento Bloom','Uma pausa curta também é cuidado.',`<div class="moment"><div><div class="quote">Respire fundo. Um passo de cada vez também te leva longe.</div>${btn('Respirar agora','primary','openBreathing()')}</div><div class="moment-symbol">🌿</div></div>`,'warm-card')}</div>
    <div class="home-grid">${card('Meu dia','Próximos compromissos',`<div class="timeline"><div><strong>14:00</strong><span>Estudar Banco de Dados</span><small>Biblioteca · 25 min</small></div><div><strong>17:30</strong><span>Trabalho em grupo</span><small>Projeto Bloom</small></div><div><strong>20:00</strong><span>Entregar relatório do TCC</span><small>Prazo hoje</small></div></div><div class="card-footer">${linkBtn('Ver agenda','/organizar/calendario')}</div>`)+
    card(recommendation[0],'Recomendação leve',`<p>${recommendation[1]}</p>${linkBtn(recommendation[2],recommendation[3],'primary')}`,'soft-card')}</div>
    ${card('Acesso rápido','As ferramentas que mais combinam com a rotina do estudante.',`<div class="quick-grid">${[['⏱️','Pomodoro','/estudar/pomodoro'],['🎯','Modo Foco','/estudar/foco'],['📔','Diário','/bem-estar/diario'],['💭','Ideias','/organizar/ideias'],['🌱','Hábitos','/organizar/habitos'],['🤝','Encontrar apoio','/bem-estar/apoio']].map(x=>`<a class="quick-card" href="#${x[2]}"><span>${x[0]}</span><b>${x[1]}</b><small>Abrir</small></a>`).join('')}</div>`)}
    <div class="home-grid">${card('Autoconhecimento','Reflexões e testes para conhecer melhor seu próprio ritmo.',`<div class="stats"><div><b>3</b><span>testes</span></div><div><b>12</b><span>reflexões</span></div><div><b>76%</b><span>evolução</span></div></div><div class="card-footer">${linkBtn('Explorar','/bem-estar/autoconhecimento','primary')}</div>`)+
    card('Precisa de ajuda?','Apoio quando você sentir que precisa.',`<div class="help-actions">${btn('SOS','danger','openSOS()')}${linkBtn('Encontrar apoio','/bem-estar/apoio')}</div>`,'help-card')}</div>`);
}
function saveMood(){if(!state.mood)return toast('Escolha como você está primeiro.');state.data.checkins.unshift({id:Date.now(),date:'Hoje',mood:state.mood,factors:['Rotina'],note:''});state.mood=null;save();render();toast('Check-in registrado.');}
function openMoodHistory(){openModal('Histórico de humor',state.data.checkins.slice(0,8).map(c=>`<div class="list-row"><div><b>${c.mood} · ${c.date}</b><small>${esc(c.note||'Sem observação')}</small></div><span class="pill">${c.factors.join(', ')}</span></div>`).join('')+`<div class="modal-actions">${btn('Fechar','secondary','closeModal()')}</div>`);}

function organizar(view='Visão geral'){return shell(pageHead('Organização pessoal','Organizar sem sobrecarregar','Uma rotina clara, sem transformar produtividade em cobrança.',btn('Capturar ideia','primary','openIdea()'))+tabs(['Visão geral','Tarefas','Calendário','Hábitos'],view,'setOrgView')+(view==='Visão geral'?organizeOverview():view==='Tarefas'?tasksPage():view==='Calendário'?calendarPage():habitsPage()));}
function setOrgView(v){const m={'Visão geral':'/organizar','Tarefas':'/organizar/tarefas','Calendário':'/organizar/calendario','Hábitos':'/organizar/habitos'};go(m[v]);}
function organizeOverview(){return `<div class="stats-row"><div class="stat"><b>${state.data.tasks.filter(t=>!t.done).length}</b><span>tarefas pendentes</span></div><div class="stat"><b>${state.data.habits.length}</b><span>hábitos</span></div><div class="stat"><b>3</b><span>compromissos hoje</span></div></div><div class="two-col"><section class="card">${cardTitle('Hoje','O que merece atenção agora')}<div class="list">${state.data.tasks.map(taskRow).join('')}</div></section><section class="card">${cardTitle('Próximos compromissos','Uma visão rápida')}<div class="timeline"><div><strong>14:00</strong><span>Estudar Banco de Dados</span><small>25 min de foco</small></div><div><strong>17:30</strong><span>Trabalho em grupo</span><small>Projeto Bloom</small></div><div><strong>20:00</strong><span>Entrega do relatório</span><small>Prazo hoje</small></div></div></section></div><section class="card idea-strip"><div><div class="kicker">Caixa de ideias</div><h2>Capture primeiro. Organize depois.</h2><p class="sub">${state.data.ideas.filter(i=>!i.archived).length} ideias ativas</p></div>${btn('Nova ideia','secondary','openIdea()')}</section>`;}
function taskRow(t){return `<div class="list-row"><div class="row-main"><button class="check-btn ${t.done?'done':''}" onclick="toggleTask(${t.id})">${t.done?'✓':''}</button><div><b class="${t.done?'strike':''}">${esc(t.title)}</b><small>${esc(t.cat)} · ${esc(t.due)}</small></div></div><div class="row-actions"><span class="pill ${t.priority==='Alta'?'red':''}">${esc(t.priority)}</span><button class="text-btn" onclick="openEditTask(${t.id})">Editar</button><button class="text-btn" onclick="deleteTask(${t.id})">Excluir</button></div></div>`;}
function tasksPage(){return card('Tarefas','Crie, edite, conclua ou remova atividades.',`<div class="list">${state.data.tasks.map(taskRow).join('')}</div><div class="card-footer">${btn('Nova tarefa','primary','openNewTask()')}${btn('Usar uma ideia','secondary','openIdeasToConvert()')}</div>`);}
function openNewTask(prefill=''){openModal('Nova tarefa',`<form onsubmit="saveTask(event)"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" value="${esc(prefill)}" required placeholder="Ex.: Revisar matéria de cálculo"></div><div class="field"><label>Categoria</label><select name="cat"><option>Estudos</option><option>TCC</option><option>Projeto</option><option>Pessoal</option></select></div><div class="field"><label>Prioridade</label><select name="priority"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></div><div class="field"><label>Prazo</label><input name="due" value="Hoje"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar tarefa</button></div></form>`);}
function saveTask(e){e.preventDefault();const f=new FormData(e.target);state.data.tasks.unshift({id:Date.now(),title:f.get('title'),cat:f.get('cat'),due:f.get('due'),priority:f.get('priority'),done:false});save();closeModal();render();toast('Tarefa criada.');}
function openEditTask(id){const t=state.data.tasks.find(x=>x.id===id);openModal('Editar tarefa',`<form onsubmit="updateTask(event,${id})"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" value="${esc(t.title)}" required></div><div class="field"><label>Categoria</label><input name="cat" value="${esc(t.cat)}"></div><div class="field"><label>Prioridade</label><select name="priority"><option ${t.priority==='Alta'?'selected':''}>Alta</option><option ${t.priority==='Média'?'selected':''}>Média</option><option ${t.priority==='Baixa'?'selected':''}>Baixa</option></select></div><div class="field"><label>Prazo</label><input name="due" value="${esc(t.due)}"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function updateTask(e,id){e.preventDefault();const t=state.data.tasks.find(x=>x.id===id),f=new FormData(e.target);Object.assign(t,{title:f.get('title'),cat:f.get('cat'),priority:f.get('priority'),due:f.get('due')});save();closeModal();render();toast('Tarefa atualizada.');}
function toggleTask(id){const t=state.data.tasks.find(x=>x.id===id);t.done=!t.done;save();render();toast(t.done?'Tarefa concluída.':'Tarefa reaberta.');}
function deleteTask(id){state.data.tasks=state.data.tasks.filter(x=>x.id!==id);save();render();toast('Tarefa excluída.');}
function openIdeasToConvert(){const ideas=state.data.ideas.filter(i=>!i.archived);openModal('Transformar ideia em tarefa',ideas.length?ideas.map(i=>`<div class="list-row"><div><b>${esc(i.text)}</b><small>${i.kind}</small></div>${btn('Transformar','secondary',`ideaToTask(${i.id})`)}</div>`).join(''):'<div class="empty">Não há ideias ativas.</div>');}
function ideaToTask(id){const i=state.data.ideas.find(x=>x.id===id);state.data.tasks.unshift({id:Date.now(),title:i.text,cat:'Ideia convertida',due:'Hoje',priority:'Média',done:false});i.archived=true;save();closeModal();go('/organizar/tarefas');toast('Ideia transformada em tarefa.');}
function openIdea(){openModal('Capturar ideia',`<form onsubmit="saveIdea(event)"><div class="field"><label>Ideia, pensamento ou lembrete</label><textarea name="text" rows="5" required placeholder="Escreva algo para não precisar guardar na cabeça."></textarea></div><div class="chips"><button type="button" class="chip" onclick="toast('Áudio demonstrativo iniciado.')">🎙️ Gravar áudio</button></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar ideia</button></div></form>`);}
function saveIdea(e){e.preventDefault();const f=new FormData(e.target);state.data.ideas.unshift({id:Date.now(),text:f.get('text'),kind:'Ideia',archived:false});save();closeModal();toast('Ideia capturada.');}
function calendarPage(){return card('Calendário pessoal','Visualize compromissos, tarefas e eventos acadêmicos.',`<div class="calendar-toolbar"><b>Setembro 2026</b>${btn('Hoje','secondary','toast(\'Hoje selecionado.\')')}</div><div class="calendar-grid">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${Array.from({length:35},(_,i)=>{const d=i<24?i+1:i-24,m=i>=24;const hit=d===14||d===16||d===20;return `<button class="cal-day ${m?'muted-day':''} ${d===10&&!m?'today':''}" onclick="showCalendarDay(${d})"><b>${d}</b>${hit&&!m?`<span>${d===14?'Banco de Dados':d===16?'Grupo de estudos':'Campanha'}</span>`:''}</button>`}).join('')}</div>`);}
function showCalendarDay(day){openModal(`Agenda do dia ${day}/09`,`<div class="list-row"><div><b>${day===14?'Estudar Banco de Dados':day===16?'Grupo de estudos':day===20?'Semana do Bem-estar':'Sem compromisso principal'}</b><small>${day===14?'14:00 · 25 min':day===16?'18:00 · Biblioteca':'Dia livre até o momento'}</small></div></div><div class="modal-actions">${btn('Nova tarefa','primary','closeModal();openNewTask()')}${btn('Fechar','secondary','closeModal()')}</div>`);}
function habitsPage(){return `<div class="two-col"><section class="card">${cardTitle('Hábitos','Metas simples para acompanhar sem culpa.')}<div class="list">${state.data.habits.map(h=>`<div class="list-row"><div class="row-main"><div class="habit-icon">${habitIcon(h.title)}</div><div><b>${esc(h.title)}</b><small>${esc(h.goal)} · ${esc(h.freq)}</small></div></div><div class="habit-progress"><div class="progress"><span style="width:${h.progress}%"></span></div>${btn(h.checked?'Feito':'Registrar','secondary',`markHabit(${h.id})`)}</div></div>`).join('')}</div><div class="card-footer">${btn('Novo hábito','primary','openHabit()')}</div></section><section class="card soft-card"><div class="kicker">Constância</div><h2>O progresso não precisa ser perfeito.</h2><p class="sub">Use os hábitos para perceber o que funciona no seu ritmo.</p><div class="big-stat">12 <span>dias de prática</span></div></section></div>`;}
function habitIcon(t){return t.includes('água')?'💧':t.includes('Dormir')?'🌙':t.includes('Movimentar')?'🌿':'📚';}
function openHabit(){openModal('Novo hábito',`<form onsubmit="saveHabit(event)"><div class="form-grid"><div class="field full"><label>Nome</label><input name="title" required placeholder="Ex.: Caminhar 20 minutos"></div><div class="field"><label>Meta</label><input name="goal" placeholder="20 min"></div><div class="field"><label>Frequência</label><select name="freq"><option>Diário</option><option>3x por semana</option><option>5x por semana</option></select></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar hábito</button></div></form>`);}
function saveHabit(e){e.preventDefault();const f=new FormData(e.target);state.data.habits.push({id:Date.now(),title:f.get('title'),goal:f.get('goal'),freq:f.get('freq'),progress:0,checked:false});save();closeModal();render();toast('Hábito adicionado.');}
function markHabit(id){const h=state.data.habits.find(x=>x.id===id);h.checked=!h.checked;h.progress=h.checked?Math.min(100,h.progress+5):Math.max(0,h.progress-5);save();render();}

function estudar(view='Visão geral'){return shell(pageHead('Estudos','Estudar com equilíbrio','Foco, pausas e acompanhamento — sem excesso de informação.',linkBtn('Modo Foco','/estudar/foco','primary'))+tabs(['Visão geral','Pomodoro','Modo Foco','Progresso'],view,'setStudyView')+(view==='Visão geral'?studyOverview():view==='Pomodoro'?pomodoroPage():view==='Modo Foco'?focusPage():progressPage()));}
function setStudyView(v){const m={'Visão geral':'/estudar','Pomodoro':'/estudar/pomodoro','Modo Foco':'/estudar/foco','Progresso':'/estudar/progresso'};go(m[v]);}
function studyOverview(){return `<div class="two-col"><section class="card pomo-card">${cardTitle('Foco de hoje','Uma sessão por vez.')}<div class="pomo-ring"><div><small>${state.timer.mode}</small><strong>${formatTime(state.timer.seconds)}</strong></div></div><div class="head-actions center">${btn(state.timer.running?'Pausar':'Iniciar foco','primary','toggleTimer()')}${btn('Reiniciar','secondary','resetTimer()')}</div><div class="focus-tools"><button class="tool-chip" onclick="selectSound('rain')">🌧️ Chuva</button><button class="tool-chip" onclick="selectSound('forest')">🌲 Floresta</button><button class="tool-chip" onclick="selectSound('cafe')">☕ Café</button><span class="sound-state">${state.sound?`Som: ${soundName(state.sound)}`:'Sem som'}</span></div></section><section class="card">${cardTitle('Seu progresso','Esta semana')}<div class="stats big"><div><b>6h20</b><span>tempo estudado</span></div><div><b>14</b><span>Pomodoros</span></div><div><b>82%</b><span>meta semanal</span></div></div><div class="chart">${[42,62,35,88,52,74,60].map((v,i)=>`<div><i style="height:${v}%"></i><small>${['S','T','Q','Q','S','S','D'][i]}</small></div>`).join('')}</div></section></div><section class="card soft-card" style="margin-top:18px"><div class="kicker">Dica de foco</div><h2>Comece com a próxima ação, não com a tarefa inteira.</h2><p class="sub">Abra o Modo Foco e escolha uma atividade específica quando quiser reduzir distrações.</p></section>`;}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function soundName(id){return ({rain:'Chuva suave',forest:'Floresta',cafe:'Café',waves:'Ondas',wind:'Vento',white:'Ruído branco'})[id]||id;}
function selectSound(id){state.sound=id;render();toast(`Som: ${soundName(id)}.`);}
function pomodoroPage(){return `<div class="two-col"><section class="card pomo-card">${cardTitle('Pomodoro','Configure seu ritmo.')}<div class="pomo-ring"><div><small>${state.timer.mode}</small><strong>${formatTime(state.timer.seconds)}</strong></div></div><div class="head-actions center">${btn(state.timer.running?'Pausar':'Iniciar foco','primary','toggleTimer()')}${btn('Reiniciar','secondary','resetTimer()')}</div><div class="mode-row"><button class="mode ${state.timer.mode==='25/5'?'active':''}" onclick="setTimerMode('25/5')">25 / 5</button><button class="mode ${state.timer.mode==='50/10'?'active':''}" onclick="setTimerMode('50/10')">50 / 10</button><button class="mode ${state.timer.mode==='custom'?'active':''}" onclick="setTimerMode('custom')">Personalizado</button></div></section><section class="card">${cardTitle('Histórico recente','Sessões registradas localmente.')}<div class="list"><div class="list-row"><div><b>Ontem · Banco de Dados</b><small>25 min · concluído</small></div><span class="pill">Concluído</span></div><div class="list-row"><div><b>Ontem · TCC</b><small>50 min · concluído</small></div><span class="pill">Concluído</span></div></div></section></div>`;}
function setTimerMode(mode){if(mode==='custom')return openModal('Pomodoro personalizado',`<form onsubmit="customTimer(event)"><div class="form-grid"><div class="field"><label>Foco (min)</label><input name="focus" type="number" min="1" max="120" value="25" required></div><div class="field"><label>Pausa (min)</label><input name="break" type="number" min="1" max="60" value="5" required></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Aplicar</button></div></form>`);state.timer.mode=mode;state.timer.seconds=mode==='50/10'?3000:1500;render();}
function customTimer(e){e.preventDefault();const f=new FormData(e.target);state.timer.mode=`${f.get('focus')}/${f.get('break')}`;state.timer.seconds=Number(f.get('focus'))*60;closeModal();render();toast('Pomodoro personalizado aplicado.');}
function toggleTimer(){state.timer.running=!state.timer.running;clearInterval(state.timer.interval);if(state.timer.running){state.timer.interval=setInterval(()=>{if(state.timer.seconds>0){state.timer.seconds--;render();}else{resetTimer();toast('Sessão concluída. Hora de pausar. 🌿');}},1000);}render();}
function resetTimer(){clearInterval(state.timer.interval);state.timer.running=false;state.timer.seconds=state.timer.mode==='50/10'?3000:1500;render();}
function focusPage(){return `<section class="card focus-screen"><div class="kicker">Modo Foco</div><h2>Banco de Dados</h2><div class="focus-time">${formatTime(state.timer.seconds)}</div><p class="sub">${state.sound?`Som ambiente: ${soundName(state.sound)}`:'Sem som selecionado'}</p><div class="head-actions center">${btn(state.timer.running?'Pausar':'Iniciar foco','primary','toggleTimer()')}${btn('Encerrar sessão','secondary','resetTimer()')}</div><div class="focus-tip"><b>🌿 Lembrete</b><span>Seu desempenho não precisa ser perfeito para que a sessão tenha valor.</span></div></section>`;}
function progressPage(){return `<div class="stats-row"><div class="stat"><b>6h20</b><span>horas estudadas</span></div><div class="stat"><b>14</b><span>Pomodoros</span></div><div class="stat"><b>18</b><span>tarefas concluídas</span></div><div class="stat"><b>82%</b><span>meta semanal</span></div></div><section class="card" style="margin-top:18px">${cardTitle('Evolução semanal','Observe o ritmo, não apenas o resultado.')}<div class="chart tall">${[38,55,47,75,58,92,68].map((v,i)=>`<div><i style="height:${v}%"></i><small>${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'][i]}</small></div>`).join('')}</div></section>`;}

function bemEstar(view='Hoje'){return shell(pageHead('Bem-estar','Cuide de você no seu ritmo','Perceber, respirar, refletir e encontrar apoio quando precisar.')+tabs(['Hoje','Diário','Autoconhecimento','Práticas','Apoio'],view,'setWellView')+(view==='Hoje'?wellToday():view==='Diário'?diaryPage():view==='Autoconhecimento'?selfKnowledge():view==='Práticas'?practicesPage():supportPage()));}
function setWellView(v){const m={'Hoje':'/bem-estar','Diário':'/bem-estar/diario','Autoconhecimento':'/bem-estar/autoconhecimento','Práticas':'/bem-estar/praticas','Apoio':'/bem-estar/apoio'};go(m[v]);}
function wellToday(){return `<div class="two-col"><section class="card">${cardTitle('Como você está hoje?','O registro é para autopercepção, não diagnóstico.')}<div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(([i,t])=>`<button class="mood ${state.mood===i?'selected':''}" onclick="state.mood='${i}';render()"><span>${i}</span>${t}</button>`).join('')}</div><div class="field"><label>O que influenciou seu dia?</label><textarea id="moodNote" rows="4" placeholder="Aulas, provas, descanso, conversas..."></textarea></div><div class="modal-actions">${btn('Salvar check-in','primary','saveMoodDetailed()')}</div></section><section class="card soft-card">${cardTitle('Recomendação de hoje','Uma sugestão, não uma cobrança.')}<div class="recommend-list"><div class="recommend"><span>🌬️</span><div><b>Respiração</b><p>Um minuto de pausa antes da próxima atividade.</p>${btn('Começar','secondary','openBreathing()')}</div></div><div class="recommend"><span>📔</span><div><b>Escrever</b><p>Registre em uma frase como foi seu dia.</p>${linkBtn('Abrir diário','/bem-estar/diario')}</div></div></div></section></div><div class="two-col compact-gap" style="margin-top:18px">${card('Últimos registros','Seus registros mais recentes.',`<div class="list">${state.data.checkins.slice(0,2).map(c=>`<div class="list-row"><div><b>${c.mood} · ${c.date}</b><small>${esc(c.note||'Sem observação')}</small></div><span class="pill">${c.factors.join(', ')}</span></div>`).join('')}</div>`)+card('Hábitos de hoje','Pequenas práticas.',`<div class="list">${state.data.habits.slice(0,3).map(h=>`<div class="list-row"><div><b>${habitIcon(h.title)} ${esc(h.title)}</b><small>${h.progress}% da meta</small></div><button class="text-btn" onclick="markHabit(${h.id})">${h.checked?'Desfazer':'Registrar'}</button></div>`).join('')}</div>`)}</div>`;}
function saveMoodDetailed(){if(!state.mood)return toast('Escolha uma emoção primeiro.');const note=$('#moodNote')?.value.trim()||'';state.data.checkins.unshift({id:Date.now(),date:'Hoje',mood:state.mood,factors:['Rotina'],note});state.mood=null;save();render();toast('Check-in registrado.');}
function diaryPage(){return `<div class="two-col"><section class="card">${cardTitle('Diário pessoal','Escreva, registre e volte quando quiser.',btn('Novo registro','primary','openDiary()'))}<div class="list">${state.data.diary.map(d=>`<article class="diary-item"><div class="diary-meta"><span>${d.mood}</span><small>${d.date}</small></div><div><b>${esc(d.title)}</b><p>${esc(d.text)}</p><div class="row-actions"><button class="text-btn" onclick="openDiary(${d.id})">Editar</button><button class="text-btn" onclick="deleteDiary(${d.id})">Excluir</button></div></div></article>`).join('')}</div></section><section class="card soft-card"><div class="kicker">Privacidade</div><h2>Um espaço pessoal dentro do Bloom.</h2><p class="sub">Registros pessoais devem permanecer separados dos dados compartilhados com a instituição.</p></section></div>`;}
function openDiary(id=null){const d=id?state.data.diary.find(x=>x.id===id):null;openModal(id?'Editar registro':'Novo registro',`<form onsubmit="saveDiary(event,${id||0})"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" value="${esc(d?.title||'')}" required></div><div class="field full"><label>Texto</label><textarea name="text" rows="7" required>${esc(d?.text||'')}</textarea></div><div class="field"><label>Imagem</label><input type="file" accept="image/*"></div><div class="field"><label>Áudio</label><input type="file" accept="audio/*"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar registro</button></div></form>`);}
function saveDiary(e,id){e.preventDefault();const f=new FormData(e.target);if(id)Object.assign(state.data.diary.find(x=>x.id===id),{title:f.get('title'),text:f.get('text')});else state.data.diary.unshift({id:Date.now(),title:f.get('title'),date:'Hoje',mood:state.mood||'🌱',text:f.get('text')});save();closeModal();render();toast('Registro salvo.');}
function deleteDiary(id){state.data.diary=state.data.diary.filter(x=>x.id!==id);save();render();toast('Registro excluído.');}
function selfKnowledge(){return `<div class="two-col"><section class="card">${cardTitle('Autoconhecimento','Reflexões e questionários como convite à observação.')}<div class="reflection-list">${[['🌱','Meu ritmo de energia','8 perguntas'],['🧭','Como organizo meu tempo','10 perguntas'],['💭','O que me ajuda a estudar','6 perguntas']].map((x,i)=>`<div class="reflection"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div>${btn('Abrir','secondary',`openQuiz(${i})`)}</div>`).join('')}</div></section><section class="card soft-card">${cardTitle('Seus resultados','Apresentados como reflexão pessoal.')}<div class="result-grid"><div><b>3</b><span>testes concluídos</span></div><div><b>12</b><span>reflexões</span></div><div><b>76%</b><span>evolução</span></div></div><p class="sub">Os resultados não representam diagnóstico psicológico.</p></section></div>`;}
function openQuiz(i){const qs=[['Meu ritmo de energia',['Ter uma primeira ação pequena','Ter tudo planejado','Fazer junto com alguém']],['Como organizo meu tempo',['Priorizar poucas coisas','Reorganizar os horários','Pedir apoio']],['O que me ajuda a estudar',['Silêncio','Som ambiente','Movimento ao redor']]][i];openModal(qs[0],`<p class="sub">Escolha a resposta que mais combina com você agora.</p><div class="answer-list">${qs[1].map(a=>`<button class="answer" onclick="finishQuiz()">${a}</button>`).join('')}</div>`);}
function finishQuiz(){closeModal();toast('Reflexão registrada.');}
function practicesPage(){return `<div class="practice-grid">${[['🌬️','Respiração','1–3 min','Regule o ritmo da respiração.','openBreathing()'],['🧘','Meditação','5 min','Uma pausa guiada para desacelerar.','openPractice(\'Meditação\')'],['⏸️','Pausa consciente','2 min','Saia da tela, alongue e volte com calma.','openPractice(\'Pausa consciente\')'],['🌙','Relaxamento','8 min','Uma rotina curta para encerrar o dia.','openPractice(\'Relaxamento\')']].map(x=>`<article class="card practice"><span class="practice-icon">${x[0]}</span><div><h2>${x[1]}</h2><span class="pill">${x[2]}</span><p class="sub">${x[3]}</p></div>${btn('Começar','secondary',x[4])}</article>`).join('')}</div>`;}
function openPractice(name){openModal(name,`<div class="practice-modal"><div class="practice-orb">🌿</div><h3>Vamos começar com calma.</h3><p class="sub">Este exercício é demonstrativo e pode ser interrompido a qualquer momento.</p>${btn('Iniciar','primary','toast(\'Prática iniciada.\');closeModal()')}</div>`);}
function openBreathing(){openModal('Respire no seu ritmo',`<div class="practice-modal"><div class="practice-orb breathing">🌿</div><h3>Inspire 4s · segure 2s · expire 6s</h3><p class="sub">Repita algumas vezes, sem precisar acertar perfeitamente.</p>${btn('Começar','primary','toast(\'Prática iniciada.\');closeModal()')}</div>`);}
function supportPage(){return `<div class="two-col"><section class="card">${cardTitle('Encontrar apoio','Serviços demonstrativos dentro de um raio de referência.')}<div class="support-filters"><button class="filter active">Até 10 km</button><button class="filter">Até 25 km</button><button class="filter">Até 50 km</button></div><div class="list">${state.data.supportServices.map(s=>`<article class="service"><div class="service-icon">🤝</div><div class="service-body"><div class="service-top"><div><b>${esc(s.name)}</b><small>${esc(s.category)}</small></div><span class="pill">${s.distance}</span></div><p>${esc(s.address)}</p><div class="service-meta"><span>★ ${s.rating}</span><span>${s.hours}</span></div><div class="row-actions">${btn('Detalhes','secondary',`openService(${s.id})`)}${btn('Ligar','secondary',`toast('Ligação demonstrativa.')`)}${btn('WhatsApp','secondary',`toast('WhatsApp demonstrativo.')`)}</div></div></article>`).join('')}</div></section><section class="card soft-card">${cardTitle('Apoio da instituição','Quando você preferir falar com alguém da sua própria comunidade.')}<div class="list">${state.data.supportRequests.map(r=>`<div class="support-request"><div class="request-icon">💚</div><div><b>${esc(r.type)}</b><small>${r.date} · ${esc(r.person)}</small><p>${esc(r.summary)}</p><span class="pill terracotta">${esc(r.status)}</span><div class="support-track"><i class="done"></i><i class="done"></i><i></i><i></i><i></i></div></div></div>`).join('')}</div><div class="card-footer">${btn('Solicitar apoio','primary','openSupportRequest()')}</div></section></div>`;}
function openService(id){const s=state.data.supportServices.find(x=>x.id===id);openModal(s.name,`<div class="service-detail"><span class="pill">${s.distance}</span><p>${s.category}</p><p><b>Endereço:</b> ${s.address}</p><p><b>Avaliação:</b> ★ ${s.rating}</p><p><b>Horário:</b> ${s.hours}</p><p><b>Telefone:</b> ${s.phone}</p><div class="head-actions">${btn('Abrir mapa','secondary','toast(\'Mapa demonstrativo aberto.\')')}${btn('Ligar','secondary','toast(\'Ligação demonstrativa.\')')}${btn('WhatsApp','primary','toast(\'WhatsApp demonstrativo.\')')}</div></div>`);}
function openSupportRequest(){openModal('Solicitar apoio',`<form onsubmit="saveSupportRequest(event)"><div class="form-grid"><div class="field"><label>Tipo</label><select name="type"><option>Orientação</option><option>Psicológico</option><option>Acadêmico</option><option>Coordenação</option></select></div><div class="field"><label>Preferência</label><select name="preference"><option>Online</option><option>Presencial</option><option>Tanto faz</option></select></div><div class="field full"><label>O que você precisa?</label><textarea name="summary" rows="5" required></textarea></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Enviar solicitação</button></div></form>`);}
function saveSupportRequest(e){e.preventDefault();const f=new FormData(e.target);state.data.supportRequests.unshift({id:Date.now(),date:'Hoje',type:f.get('type'),person:'Setor de acolhimento',status:'Solicitada',summary:f.get('summary')});save();closeModal();render();toast('Solicitação enviada.');}

function instituicao(view='Visão geral'){return shell(pageHead('Vida acadêmica','Sua instituição, mais perto','Informações acadêmicas e espaços de participação, sem poluir a navegação.',btn('Vincular instituição','secondary','openInstitutionLink()'))+tabs(['Visão geral','Agenda','Apoio','Comunidade','Comunicação'],view,'setInstView')+(view==='Visão geral'?institutionOverview():view==='Agenda'?academicAgenda():view==='Apoio'?institutionSupport():view==='Comunidade'?communitiesPage():communicationPage()));}
function setInstView(v){const m={'Visão geral':'/instituicao','Agenda':'/instituicao/agenda','Apoio':'/instituicao/apoio','Comunidade':'/instituicao/comunidade','Comunicação':'/instituicao/comunicacao'};go(m[v]);}
function institutionOverview(){return `<div class="two-col"><section class="card soft-card">${cardTitle(state.data.user.institution?'Instituição vinculada':'Nenhuma instituição vinculada','Você controla o vínculo e o que recebe.')}<div class="institution-head"><div class="institution-mark">🏫</div><div><h2>${esc(state.data.user.institution||'Vincule sua instituição')}</h2><p class="sub">${esc(state.data.user.course)} · ${esc(state.data.user.className)}</p></div></div></section><section class="card">${cardTitle('Atalhos institucionais','Só o essencial para resolver as coisas.')}<div class="institution-shortcuts"><button onclick="go('/instituicao/agenda')">📅<b>Agenda acadêmica</b><span>Provas e atividades</span></button><button onclick="go('/instituicao/apoio')">🤝<b>Apoio e acolhimento</b><span>Solicitar ajuda</span></button><button onclick="go('/instituicao/comunidade')">💬<b>Comunidade</b><span>Grupos e participação</span></button><button onclick="go('/instituicao/comunicacao')">📣<b>Comunicação</b><span>Avisos e campanhas</span></button></div></section></div><div class="two-col" style="margin-top:18px"><section class="card">${cardTitle('Participação','Feedback e segurança ficam aqui, sem ocupar a navegação principal.')}<div class="participation-grid"><button onclick="openFeedback()"><b>📝 Feedback</b><span>Avalie matérias, professores e carga.</span></button><button onclick="openReport()"><b>🛡️ Denúncia</b><span>Canal restrito para situações graves.</span></button></div></section><section class="card peach-card">${cardTitle('Encerrar integração','Veja o que acontece antes de confirmar.')}<p class="sub">Novos avisos e eventos deixam de chegar. Seus registros pessoais continuam privados.</p>${btn('Gerenciar vínculo','secondary','openUnlink()')}</section></div>`;}
function openInstitutionLink(){openModal('Vincular instituição',`<div class="field"><label>Código ou convite</label><input id="inviteCode" placeholder="Ex.: BLOOM-2026"></div><div class="link-preview"><b>Universidade Bloom</b><small>Campinas, SP · exemplo demonstrativo</small></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="confirmInstitutionLink()">Vincular</button></div>`);}
function confirmInstitutionLink(){state.data.user.institution='Universidade Bloom';save();closeModal();render();toast('Instituição vinculada.');}
function openUnlink(){openModal('Encerrar integração',`<div class="notice-box"><b>Antes de confirmar</b><p>Você deixará de receber novos avisos e eventos. Dados pessoais e registros de bem-estar continuam separados.</p></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn danger" onclick="unlinkInstitution()">Confirmar encerramento</button></div>`);}
function unlinkInstitution(){state.data.user.institution='';save();closeModal();render();toast('Vínculo encerrado.');}
function academicAgenda(){return `<section class="card">${cardTitle('Agenda acadêmica','Itens recebidos da instituição.')}<div class="grid-3">${[['📘','Prova de Banco de Dados','14/09 · Sala 204'],['📝','Entrega do projeto integrador','18/09 · Portal do aluno'],['🏫','Palestra sobre carreira','20/09 · Auditório']].map(x=>`<article class="event-card"><div class="event-icon">${x[0]}</div><h3>${x[1]}</h3><p class="sub">${x[2]}</p>${btn('Adicionar ao calendário','secondary','toast(\'Evento adicionado ao calendário.\')')}</article>`).join('')}</div></section><section class="card" style="margin-top:18px">${cardTitle('Eventos e campanhas','Adicione, confirme ou cancele participação.')}<div class="grid-3">${state.data.events.map(e=>`<article class="event-card"><div><span class="pill">${e.date}</span><h3>${esc(e.title)}</h3><p class="sub">${esc(e.where)}</p></div><div class="row-actions">${btn(e.joined?'Cancelar':'Participar',e.joined?'secondary':'primary',`toggleEvent(${e.id})`)}${btn(e.reminder?'Lembrete ativo':'Lembrete',e.reminder?'primary':'secondary',`toggleReminder(${e.id})`)}${btn('Detalhes','secondary',`openEvent(${e.id})`)}</div></article>`).join('')}</div></section>`;}
function toggleEvent(id){const e=state.data.events.find(x=>x.id===id);e.joined=!e.joined;save();render();toast(e.joined?'Participação confirmada.':'Participação cancelada.');}
function toggleReminder(id){const e=state.data.events.find(x=>x.id===id);e.reminder=!e.reminder;save();render();toast(e.reminder?'Lembrete ativado.':'Lembrete desativado.');}
function openEvent(id){const e=state.data.events.find(x=>x.id===id);openModal(e.title,`<p class="sub">${esc(e.details)}</p><p><b>Quando:</b> ${e.date}</p><p><b>Onde:</b> ${esc(e.where)}</p><div class="field"><label>Pergunta anônima</label><textarea id="eventQuestion" rows="4" placeholder="Digite uma pergunta para a organização..."></textarea></div><div class="modal-actions">${btn('Enviar pergunta','secondary','submitEventQuestion()')}${btn('Fechar','secondary','closeModal()')}</div>`);}
function submitEventQuestion(){toast('Pergunta anônima registrada.');closeModal();}
function institutionSupport(){return `<div class="two-col"><section class="card">${cardTitle('Apoio e acolhimento','Acompanhe uma solicitação sem expor detalhes pessoais.',btn('Solicitar ajuda','primary','openSupportRequest()'))}<div class="list">${state.data.supportRequests.map(r=>`<div class="support-request"><div class="request-icon">💚</div><div><b>${esc(r.type)}</b><small>${r.date} · ${esc(r.person)}</small><p>${esc(r.summary)}</p><span class="pill terracotta">${esc(r.status)}</span><div class="support-track"><i class="done"></i><i class="done"></i><i></i><i></i><i></i></div></div></div>`).join('')}</div></section><section class="card soft-card"><div class="kicker">Fluxo</div><h2>Solicitada → Em análise → Encaminhada → Atendimento → Concluída</h2><p class="sub">O estudante vê o status; o conteúdo completo não fica exposto na comunidade.</p></section></div>`;}
function communitiesPage(){return `<div class="grid-3">${state.data.communities.map(c=>`<article class="community-card"><div class="community-top"><div class="community-icon">${c.icon}</div><span class="pill">${c.members} membros</span></div><h3>${esc(c.name)}</h3><p class="sub">${esc(c.desc)}</p><div class="row-actions">${btn(c.joined?'Sair':'Entrar',c.joined?'secondary':'primary',`toggleCommunity(${c.id})`)}${c.joined?btn('Abrir','secondary',`openCommunity(${c.id})`):''}</div></article>`).join('')}</div>`;}
function toggleCommunity(id){const c=state.data.communities.find(x=>x.id===id);c.joined=!c.joined;c.members+=c.joined?1:-1;save();render();toast(c.joined?'Você entrou na comunidade.':'Você saiu da comunidade.');}
function openCommunity(id){const c=state.data.communities.find(x=>x.id===id);openModal(c.name,`<p class="sub">${esc(c.desc)}</p><div class="modal-actions">${btn('Nova publicação','primary',`newPost(${id})`)}${btn('Fechar','secondary','closeModal()')}</div><div class="list">${c.posts.length?c.posts.map((p,i)=>`<div class="post"><div class="post-meta"><b>${esc(p.author)}</b><small>${p.time}</small></div><p>${esc(p.text)}</p><div class="row-actions">${btn('♡ '+p.likes,'secondary',`likePost(${id},${i})`)}${btn('💬 '+p.comments,'secondary',`showComments(${id},${i})`)}</div></div>`).join(''):'<div class="empty">Ainda não há publicações.</div>'}</div>`);}
function newPost(id){openModal('Nova publicação',`<div class="field"><label>Mensagem</label><textarea id="postText" rows="5" placeholder="Compartilhe algo com a comunidade..."></textarea></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button>${btn('Publicar','primary',`savePost(${id})`)}</div>`);}
function savePost(id){const text=$('#postText')?.value.trim();if(!text)return toast('Digite uma mensagem.');const c=state.data.communities.find(x=>x.id===id);c.posts.unshift({author:'Ana Silva',text:text,time:'Agora',likes:0,comments:0});save();openCommunity(id);toast('Publicação criada.');}
function likePost(id,i){state.data.communities.find(c=>c.id===id).posts[i].likes++;save();openCommunity(id);}
function showComments(id,i){const c=state.data.communities.find(c=>c.id===id);openModal('Comentários',`<div class="post"><b>${esc(c.posts[i].author)}</b><p>${esc(c.posts[i].text)}</p></div><div class="field"><label>Novo comentário</label><input id="commentText" placeholder="Escreva uma resposta"></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Fechar</button>${btn('Comentar','primary',`addComment(${id},${i})`)}</div>`);}
function addComment(id,i){if(!$('#commentText')?.value.trim())return toast('Digite um comentário.');state.data.communities.find(c=>c.id===id).posts[i].comments++;save();closeModal();toast('Comentário adicionado.');}
function communicationPage(){return `<div class="two-col"><section class="card">${cardTitle('Comunicação da instituição','Avisos, campanhas e conteúdos em um só lugar.')}<div class="list">${state.data.communications.map(c=>`<article class="communication"><span class="pill">${c.type}</span><h3>${esc(c.title)}</h3><p class="sub">${esc(c.body)}</p><small>${esc(c.date)}</small><div class="card-footer">${btn('Abrir','secondary','toast(\'Conteúdo aberto.\')')}${c.type==='Campanha'?btn('Perguntar anonimamente','secondary','openAnonymousQuestion()'):''}</div></article>`).join('')}</div></section><section class="card soft-card">${cardTitle('Feedback','Sua opinião também é participação.')}<p class="sub">Avalie matérias, professores, carga de atividades, envie sugestões, elogios ou reclamações.</p>${btn('Enviar feedback','primary','openFeedback()')}</section></div>`;}
function openAnonymousQuestion(){openModal('Pergunta anônima',`<div class="field"><label>Sua pergunta</label><textarea id="anonQuestion" rows="5" placeholder="Escreva sem se identificar."></textarea></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button>${btn('Enviar','primary','toast(\'Pergunta anônima enviada.\');closeModal()')}</div>`);}
function openFeedback(){openModal('Enviar feedback',`<form onsubmit="saveFeedback(event)"><div class="form-grid"><div class="field"><label>Tipo</label><select name="type"><option>Sugestão</option><option>Elogio</option><option>Reclamação</option><option>Avaliação</option></select></div><div class="field"><label>Sobre</label><select name="target"><option>Matéria</option><option>Professor</option><option>Carga de atividades</option><option>Instituição</option></select></div><div class="field full"><label>Mensagem</label><textarea name="text" rows="5" required></textarea></div><div class="field"><label>Identificação</label><select name="anonymous"><option value="false">Identificado</option><option value="true">Anônimo</option></select></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Enviar</button></div></form>`);}
function saveFeedback(e){e.preventDefault();const f=new FormData(e.target);state.data.feedback.unshift({id:Date.now(),date:'Hoje',type:f.get('type'),target:f.get('target'),status:'Recebido'});save();closeModal();toast('Feedback enviado.');}
function openReport(){openModal('Nova denúncia',`<form onsubmit="saveReport(event)"><div class="form-grid"><div class="field"><label>Identificação</label><select name="anonymous"><option value="true">Anônima</option><option value="false">Quero me identificar</option></select></div><div class="field"><label>Tipo</label><select name="type"><option>Assédio</option><option>Violência</option><option>Discriminação</option><option>Outra situação grave</option></select></div><div class="field"><label>Data</label><input type="date" name="date"></div><div class="field"><label>Horário</label><input type="time" name="time"></div><div class="field full"><label>Local</label><input name="location" placeholder="Ex.: bloco B"></div><div class="field full"><label>Relato</label><textarea name="text" rows="6" required></textarea></div><div class="field full"><label>Provas</label><input type="file" multiple accept="image/*,audio/*,video/*"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Enviar denúncia</button></div></form>`);}
function saveReport(e){e.preventDefault();const f=new FormData(e.target);state.data.reports.unshift({id:Date.now(),code:'DEN-'+new Date().getFullYear()+'-'+String(state.data.reports.length+1).padStart(3,'0'),date:'Hoje',title:f.get('type'),anonymous:f.get('anonymous')==='true',status:'Recebida'});save();closeModal();toast('Denúncia registrada.');}

function notifications(){const n=state.data.notifications.filter(x=>!x.read).length;return shell(pageHead('Centro de notificações','Notificações','Lembretes úteis, sem criar uma seção separada só para “Lembretes”.',btn('Marcar todas como lidas','secondary','markAllRead()'))+`<div class="notice-summary"><b>${n}</b><span>não lidas</span></div><div class="notification-list">${state.data.notifications.map(x=>`<article class="notification ${x.read?'':'unread'}"><div class="notif-icon">${x.icon}</div><div><b>${esc(x.title)}</b><small>${x.time} · ${x.kind}</small></div><button class="text-btn" onclick="markRead(${x.id})">${x.read?'Lida':'Marcar como lida'}</button></article>`).join('')}</div>`);}
function markRead(id){const n=state.data.notifications.find(x=>x.id===id);n.read=true;save();render();}
function markAllRead(){state.data.notifications.forEach(x=>x.read=true);save();render();toast('Todas as notificações foram lidas.');}
function profile(){return shell(pageHead('Conta','Meu perfil','Seus dados, seu percurso e suas preferências.',linkBtn('Configurações','/configuracoes'))+`<div class="profile-grid"><aside class="card profile-side"><div class="big-avatar">AS</div><h2>${esc(state.data.user.name)}</h2><p class="sub">${esc(state.data.user.course)}</p><span class="pill">${esc(state.data.user.institution||'Sem instituição')}</span>${btn('Editar perfil','secondary','openProfileEdit()')}</aside><section class="card">${cardTitle('Resumo','Informações essenciais.')}<div class="profile-info"><div><small>E-mail</small><b>${esc(state.data.user.email)}</b></div><div><small>Turma</small><b>${esc(state.data.user.className)}</b></div><div><small>Instituição</small><b>${esc(state.data.user.institution||'Não vinculada')}</b></div></div><div class="stats big" style="margin-top:20px"><div><b>15</b><span>dias de sequência</span></div><div><b>24</b><span>sessões de foco</span></div><div><b>8</b><span>conquistas</span></div></div></section></div><section class="card" style="margin-top:18px">${cardTitle('Conquistas','Marcos leves para acompanhar seu caminho.')}<div class="achievement-grid">${[['🌱','Primeiros passos','Começou a registrar hábitos.'],['⏱️','Foco consistente','Concluiu 10 sessões.'],['💚','Momento Bloom','Registrou 7 dias de cuidado.']].map(x=>`<article><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></article>`).join('')}</div></section>`);}
function openProfileEdit(){openModal('Editar perfil',`<form onsubmit="saveProfile(event)"><div class="form-grid"><div class="field"><label>Nome</label><input name="name" value="${esc(state.data.user.name)}"></div><div class="field"><label>Curso</label><input name="course" value="${esc(state.data.user.course)}"></div><div class="field"><label>E-mail</label><input name="email" value="${esc(state.data.user.email)}"></div><div class="field"><label>Turma</label><input name="className" value="${esc(state.data.user.className)}"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function saveProfile(e){e.preventDefault();const f=new FormData(e.target);Object.assign(state.data.user,{name:f.get('name'),course:f.get('course'),email:f.get('email'),className:f.get('className')});save();closeModal();render();toast('Perfil atualizado.');}
function settings(){return shell(pageHead('Conta','Configurações','Poucas opções, claramente separadas por finalidade.')+`<div class="settings-grid"><section class="card">${cardTitle('Notificações','Escolha o que merece chegar até você.')}${settingRow('reminders','Tarefas, hábitos e compromissos','Lembretes de organização.')} ${settingRow('study','Estudos','Avisos de sessões planejadas.')} ${settingRow('wellbeing','Bem-estar','Check-ins e sugestões de pausa.')} ${settingRow('institution','Instituição','Avisos e eventos acadêmicos.')}</section><section class="card">${cardTitle('Aparência','Tema e densidade visual.')}<div class="setting-row"><div><b>Tema</b><small>Claro ou escuro.</small></div><select class="simple-select" onchange="setTheme(this.value)"><option value="light" ${state.settings.theme==='light'?'selected':''}>Claro</option><option value="dark" ${state.settings.theme==='dark'?'selected':''}>Escuro</option></select></div><div class="setting-row"><div><b>Recomendações na Home</b><small>Mostra uma única sugestão contextual.</small></div><button class="switch ${state.settings.homeRecommendations?'on':''}" onclick="toggleSetting('homeRecommendations')"><span></span></button></div></section></div><div class="settings-grid" style="margin-top:18px"><section class="card">${cardTitle('Privacidade','Controle sobre seus dados locais.')}<div class="setting-row"><div><b>Dados pessoais</b><small>Nome, e-mail, curso e turma.</small></div><span class="pill">Privado</span></div><div class="setting-row"><div><b>Registros de bem-estar</b><small>Check-ins e diário permanecem separados do vínculo institucional.</small></div><span class="pill">Privado</span></div><div class="card-footer">${btn('Gerenciar dados','secondary','openDataPrivacy()')}${btn('Termos de uso','secondary','openTerms()')}</div></section><section class="card soft-card">${cardTitle('Conta demonstrativa','Autenticação real não faz parte desta versão estática.')}<p class="sub">Esta versão existe para apresentação e navegação no GitHub Pages.</p>${btn('Sair da demonstração','secondary','toast(\'Logout demonstrativo.\')')}</section></div>`);}
function settingRow(k,t,d){return `<div class="setting-row"><div><b>${t}</b><small>${d}</small></div><button class="switch ${state.settings[k]?'on':''}" onclick="toggleSetting('${k}')"><span></span></button></div>`;}
function toggleSetting(k){state.settings[k]=!state.settings[k];save();render();toast('Preferência atualizada.');}
function setTheme(v){state.settings.theme=v;document.documentElement.dataset.theme=v;save();render();toast('Tema atualizado.');}
function openDataPrivacy(){openModal('Gerenciar dados',`<p class="sub">Os dados do protótipo ficam apenas no navegador.</p><div class="head-actions">${btn('Exportar JSON','secondary','exportData()')}${btn('Limpar dados locais','danger','clearData()')}</div>`);}
function exportData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bloom-dados.json';a.click();URL.revokeObjectURL(a.href);toast('Arquivo preparado.');}
function clearData(){localStorage.removeItem('bloom-data');location.reload();}
function openTerms(){openModal('Termos de uso',`<p class="sub">Esta demonstração foi criada para um TCC e não constitui serviço clínico nem institucional real.</p>${btn('Fechar','secondary','closeModal()')}`);}
function openSOS(){openModal('SOS',`<div class="notice-box"><b>Situação urgente?</b><p>Este fluxo é demonstrativo. Em uma versão real, o acionamento seria conectado a canais apropriados.</p></div><div class="modal-actions">${btn('Acionar SOS','danger','toast(\'SOS demonstrativo acionado.\');closeModal()')}${btn('Voltar','secondary','closeModal()')}</div>`);}
function openModal(title,body){const b=$('#modalBackdrop');$('#modal').innerHTML=`<div class="modal-head"><div><div class="kicker">Bloom</div><h2>${title}</h2></div><button class="modal-close" onclick="closeModal()">×</button></div>${body}`;b.classList.add('open');b.setAttribute('aria-hidden','false');}
function closeModal(){const b=$('#modalBackdrop');b.classList.remove('open');b.setAttribute('aria-hidden','true');}

function buildNav(){const current=route();$('#navLinks').innerHTML=NAV.map(([p,l])=>`<a href="#${p}" class="${current===p||(p!=='/'&&current.startsWith(p))?'active':''}">${l}</a>`).join('');}
function render(){state.route=route();buildNav();let v=home();switch(state.route){case'/organizar':v=organizar('Visão geral');break;case'/organizar/tarefas':v=organizar('Tarefas');break;case'/organizar/calendario':v=organizar('Calendário');break;case'/organizar/habitos':v=organizar('Hábitos');break;case'/organizar/ideias':v=organizar('Visão geral');break;case'/estudar':v=estudar('Visão geral');break;case'/estudar/pomodoro':v=estudar('Pomodoro');break;case'/estudar/foco':v=estudar('Modo Foco');break;case'/estudar/progresso':v=estudar('Progresso');break;case'/bem-estar':v=bemEstar('Hoje');break;case'/bem-estar/diario':v=bemEstar('Diário');break;case'/bem-estar/autoconhecimento':v=bemEstar('Autoconhecimento');break;case'/bem-estar/praticas':v=bemEstar('Práticas');break;case'/bem-estar/respiracao':v=bemEstar('Práticas');break;case'/bem-estar/apoio':v=bemEstar('Apoio');break;case'/instituicao':v=instituicao('Visão geral');break;case'/instituicao/agenda':v=instituicao('Agenda');break;case'/instituicao/apoio':v=instituicao('Apoio');break;case'/instituicao/comunidade':v=instituicao('Comunidade');break;case'/instituicao/comunicacao':v=instituicao('Comunicação');break;case'/notificacoes':v=notifications();break;case'/perfil':v=profile();break;case'/configuracoes':v=settings();break;}$; $('#app').innerHTML=v;window.scrollTo({top:0,behavior:'instant'});}

$('#notificationButton')?.addEventListener('click',()=>go('/notificacoes'));
$('#profileMenu')?.addEventListener('click',()=>openModal('Conta rápida',`<div class="account-menu"><a href="#/perfil" onclick="closeModal()"><span>👤</span><div><b>Meu perfil</b><small>Dados e conquistas</small></div></a><a href="#/configuracoes" onclick="closeModal()"><span>⚙️</span><div><b>Configurações</b><small>Preferências e privacidade</small></div></a></div>`));
window.addEventListener('hashchange',render);
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
$('#modalBackdrop')?.addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal();});
render();
