const $=s=>document.querySelector(s);
const data={
 user:{name:'Ana Silva',email:'ana@universidadebloom.edu.br',course:'Ciência da Computação',className:'4º semestre · Turma B',institution:'Universidade Bloom'},
 tasks:[['Estudar Banco de Dados','Estudos','Hoje','Alta',false],['Revisar introdução do TCC','TCC','Amanhã','Média',false],['Entregar relatório do grupo','Projeto','Hoje','Alta',true]],
 habits:[['Beber água','2 L por dia','Diário',70],['Dormir bem','8h por noite','Diário',86],['Movimentar o corpo','30 min','5x por semana',58],['Estudar com foco','2 sessões','Diário',75]],
 ideas:[['Pesquisar referências para o TCC','Pensamento'],['Testar sons de floresta no modo foco','Ideia']],
 diary:[['Um dia mais leve','Hoje','🙂','Consegui organizar minha tarde e fiz uma pausa antes da reunião.'],['Reflexão','Ontem','😌','Estudar em blocos menores me ajuda a começar.']],
 checkins:[['🙂','Hoje','Estudos','Dia organizado até aqui.'],['😐','Ontem','Sono','Preciso desacelerar no fim do dia.']],
 notices:[['📚','Seu foco de hoje está esperando por você.','Estudo',false],['🗓️','Você tem 3 compromissos hoje.','Agenda',false],['🌿','Que tal fazer seu check-in emocional?','Bem-estar',true],['🏫','Novo evento disponível na instituição.','Instituição',true]],
 events:[['14/09','Workshop de Projetos','Auditório principal','Instituição',false,false],['16/09','Grupo de estudos — Banco de Dados','Biblioteca','Acadêmico',true,true],['20/09','Semana do Bem-estar','Espaço de convivência','Bem-estar',false,false]],
 support:[['CAPS / Atendimento municipal','2,8 km','Atendimento em saúde mental','Rua das Flores, 120 · Centro','4,8','Seg–Sex · 08:00–18:00','(11) 4000-0101'],['Centro de acolhimento estudantil','4,1 km','Apoio psicológico e orientação','Av. da Universidade, 450','4,9','Seg–Sex · 09:00–19:00','(11) 4000-0202'],['Clínica-escola universitária','7,4 km','Atendimento acadêmico','Rua do Campus, 75','4,7','Seg–Sáb · 08:00–16:00','(11) 4000-0303']],
 communities:[['Programação','💻','Grupo de estudo para programação web',18,true],['Vestibular','🎓','Dicas e apoio para provas',34,false],['Hobbies criativos','🎨','Trocas sobre desenho, música e projetos',12,false],['Banco de Dados','📚','Revisões para avaliações',26,false],['Dificuldades acadêmicas','🗣️','Espaço para conversar e compartilhar estratégias',21,false],['Bem-estar','🌱','Pausas e hábitos saudáveis',16,false]],
 requests:[['27/08','Orientação','Setor de acolhimento','Em análise','Gostaria de conversar sobre organização e sobrecarga acadêmica.']],
 feedback:[['22/08','Sugestão','Carga de atividades','Recebido']],
 reports:[['DEN-2026-001','25/08','Situação no ambiente escolar','Anônima','Em análise']]
};
const saved=JSON.parse(localStorage.getItem('bloom-data')||'null'); if(saved) Object.assign(data,saved);
const state={timer:1500,running:false,interval:null,mood:null,theme:localStorage.getItem('bloom-theme')||'light',sound:'Chuva suave'};
document.documentElement.dataset.theme=state.theme;
function save(){localStorage.setItem('bloom-data',JSON.stringify(data));}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function path(){return (location.hash.replace(/^#/,'')||'/').split('?')[0];}
function go(p){location.hash=p;}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200);}
function btn(t,action,cls='secondary'){return `<button class="btn ${cls}" onclick="${action}">${t}</button>`}
function link(t,p,cls='secondary'){return `<a class="btn ${cls}" href="#${p}">${t}</a>`}
function modal(title,body){$('#modal').innerHTML=`<div class="modal-head"><div><div class="kicker">Bloom</div><h2>${title}</h2></div><button class="modal-close" onclick="closeModal()">×</button></div>${body}`;$('#modalBackdrop').classList.add('open');}
function closeModal(){$('#modalBackdrop').classList.remove('open');}
function page(title,desc,body,kicker='Bloom'){return `<div class="container"><div class="page-head"><div><div class="kicker">${kicker}</div><h1>${title}</h1><p>${desc}</p></div></div>${body}</div>`}
function nav(){const p=path();$('#navLinks').innerHTML=[['/','Início'],['/organizar','Organizar'],['/estudar','Estudar'],['/bem-estar','Bem-estar'],['/instituicao','Instituição']].map(x=>`<a href="#${x[0]}" class="${p===x[0]||(x[0]!=='/'&&p.startsWith(x[0]))?'active':''}">${x[1]}</a>`).join('');}
function home(){const c=data.checkins[0];const heavy=c?.[0]==='😔'||c?.[0]==='😣';return page('Bom dia, Ana!','Vamos cuidar de você hoje?',`<div class="home-grid">${card('Como você está hoje','Um check-in rápido para perceber seu momento.',`<div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(x=>`<button class="mood ${c?.[0]===x[0]||state.mood===x[0]?'selected':''}" onclick="state.mood='${x[0]}';render()"><span>${x[0]}</span>${x[1]}</button>`).join('')}</div><div class="head-actions">${btn('Fazer check-in','saveMood()','primary')}${btn('Ver histórico','moodHistory()')}</div>`,'main-card')}${card('Momento Bloom','Uma pausa curta também é cuidado.',`<div class="moment"><div><div class="quote">Respire fundo. Um passo de cada vez também te leva longe.</div>${btn('Respirar agora','openBreathing()','primary')}</div><span class="moment-symbol">🌿</span></div>`,'warm-card')}</div><div class="home-grid compact-gap">${card('Meu dia','Próximos compromissos',`<div class="timeline"><div><strong>14:00</strong><span>Estudar Banco de Dados</span><small>Biblioteca · 25 min</small></div><div><strong>17:30</strong><span>Trabalho em grupo</span><small>Projeto Bloom</small></div><div><strong>20:00</strong><span>Entregar relatório do TCC</span><small>Prazo hoje</small></div></div>${link('Ver agenda','/organizar/calendario')}`)}${card(heavy?'Um cuidado para agora':'Uma sugestão para hoje','Uma orientação, não uma cobrança.',`<p>${heavy?'Seu dia parece mais pesado. Uma pausa curta pode ser um bom próximo passo.':'Comece por uma tarefa pequena. Depois, escolha se quer continuar ou pausar.'}</p>${heavy?link('Fazer uma pausa','/bem-estar/praticas','primary'):link('Organizar meu dia','/organizar','primary')}`,'soft-card')}</div>${card('Acesso rápido','Só as ferramentas mais úteis.',`<div class="quick-grid">${[['⏱️','Pomodoro','/estudar/pomodoro'],['🎯','Modo Foco','/estudar/foco'],['📔','Diário','/bem-estar/diario'],['💭','Ideias','/organizar/ideias'],['🌱','Hábitos','/organizar/habitos'],['🤝','Encontrar apoio','/bem-estar/apoio']].map(x=>`<a class="quick-card" href="#${x[2]}"><span>${x[0]}</span><b>${x[1]}</b><small>Abrir</small></a>`).join('')}</div>`)}<div class="home-grid compact-gap">${card('Autoconhecimento','Reflexões e testes para conhecer melhor seu próprio ritmo.',`<div class="stats"><div><b>3</b><span>testes</span></div><div><b>12</b><span>reflexões</span></div><div><b>76%</b><span>evolução</span></div></div>${link('Explorar','/bem-estar/autoconhecimento','primary')}`)}${card('Precisa de ajuda?','Apoio quando você sentir que precisa.',`<div class="help-actions">${btn('SOS','openSOS()','danger')}${link('Encontrar apoio','/bem-estar/apoio')}</div>`,'help-card')}</div>`,'Seu espaço de cuidado');}
function card(t,d,b,c=''){return `<section class="card ${c}"><div class="card-title"><div><h2>${t}</h2><div class="sub">${d}</div></div></div>${b}</section>`}
function organize(view='Visão geral'){const tabs=['Visão geral','Tarefas','Calendário','Hábitos'];return page('Organizar sem sobrecarregar','Uma rotina clara, sem transformar produtividade em cobrança.',tabsHtml(tabs,view,'orgTab')+(view==='Visão geral'?orgOverview():view==='Tarefas'?tasks():view==='Calendário'?calendar():habits()),'Organização pessoal');}
function tabsHtml(a,c,fn){return `<div class="tabs">${a.map(x=>`<button class="tab ${x===c?'active':''}" onclick="${fn}('${x}')">${x}</button>`).join('')}</div>`}
function orgTab(v){go(v==='Visão geral'?'/organizar':v==='Tarefas'?'/organizar/tarefas':v==='Calendário'?'/organizar/calendario':'/organizar/habitos');}
function orgOverview(){return `<div class="stats-row"><div class="stat"><b>${data.tasks.filter(x=>!x[4]).length}</b><span>tarefas pendentes</span></div><div class="stat"><b>${data.habits.length}</b><span>hábitos</span></div><div class="stat"><b>3</b><span>compromissos hoje</span></div></div><div class="two-col">${card('Hoje','O que merece atenção agora',`<div class="list">${data.tasks.map(taskRow).join('')}</div>`)}${card('Caixa de ideias','Capture primeiro. Organize depois.',`<div class="list">${data.ideas.map((i,idx)=>`<div class="list-row"><div><b>${esc(i[0])}</b><small>${i[1]}</small></div>${btn('Virar tarefa',`ideaToTask(${idx})`)}</div>`).join('')}</div>${btn('Nova ideia','openIdea()','primary')}`)}</div>`;}
function taskRow(t,i){return `<div class="list-row"><div class="row-main"><button class="check-btn ${t[4]?'done':''}" onclick="toggleTask(${i})">${t[4]?'✓':''}</button><div><b class="${t[4]?'strike':''}">${esc(t[0])}</b><small>${esc(t[1])} · ${esc(t[2])}</small></div></div><div class="row-actions"><span class="pill ${t[3]==='Alta'?'red':''}">${t[3]}</span>${btn('Editar',`editTask(${i})`)}${btn('Excluir',`deleteTask(${i})`)}</div></div>`;}
function tasks(){return card('Tarefas','Crie, edite, conclua ou remova atividades.',`<div class="list">${data.tasks.map(taskRow).join('')}</div><div class="card-footer">${btn('Nova tarefa','openNewTask()','primary')}${btn('Usar uma ideia','openIdeas()')}</div>`)}
function openNewTask(prefill=''){modal('Nova tarefa',`<form onsubmit="saveTask(event)"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" value="${esc(prefill)}" required></div><div class="field"><label>Categoria</label><select name="cat"><option>Estudos</option><option>TCC</option><option>Projeto</option><option>Pessoal</option></select></div><div class="field"><label>Prioridade</label><select name="priority"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></div><div class="field"><label>Prazo</label><input name="due" value="Hoje"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function saveTask(e){e.preventDefault();const f=new FormData(e.target);data.tasks.unshift([f.get('title'),f.get('cat'),f.get('due'),f.get('priority'),false]);save();closeModal();render();toast('Tarefa criada.');}
function editTask(i){const t=data.tasks[i];openModalEditTask(i,t);}
function openModalEditTask(i,t){modal('Editar tarefa',`<form onsubmit="updateTask(event,${i})"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" value="${esc(t[0])}" required></div><div class="field"><label>Categoria</label><input name="cat" value="${esc(t[1])}"></div><div class="field"><label>Prioridade</label><select name="priority"><option ${t[3]==='Alta'?'selected':''}>Alta</option><option ${t[3]==='Média'?'selected':''}>Média</option><option ${t[3]==='Baixa'?'selected':''}>Baixa</option></select></div><div class="field"><label>Prazo</label><input name="due" value="${esc(t[2])}"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function updateTask(e,i){e.preventDefault();const f=new FormData(e.target);data.tasks[i]=[f.get('title'),f.get('cat'),f.get('due'),f.get('priority'),data.tasks[i][4]];save();closeModal();render();toast('Tarefa atualizada.');}
function toggleTask(i){data.tasks[i][4]=!data.tasks[i][4];save();render();}
function deleteTask(i){data.tasks.splice(i,1);save();render();toast('Tarefa excluída.');}
function openIdeas(){modal('Transformar uma ideia em tarefa',data.ideas.filter(x=>!x[2]).map((x,i)=>`<div class="list-row"><div><b>${esc(x[0])}</b><small>${x[1]}</small></div>${btn('Transformar',`ideaToTask(${i})`)}</div>`).join('')||'<div class="empty">Nenhuma ideia ativa.</div>');}
function ideaToTask(i){const x=data.ideas[i];data.tasks.unshift([x[0],'Ideia convertida','Hoje','Média',false]);data.ideas.splice(i,1);save();closeModal();go('/organizar/tarefas');}
function openIdea(){modal('Capturar ideia',`<form onsubmit="saveIdea(event)"><div class="field"><label>Ideia, pensamento ou lembrete</label><textarea name="text" rows="5" required></textarea></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function saveIdea(e){e.preventDefault();const f=new FormData(e.target);data.ideas.unshift([f.get('text'),'Ideia']);save();closeModal();toast('Ideia capturada.');}
function calendar(){return card('Calendário pessoal','Tarefas, compromissos e eventos acadêmicos.',`<div class="calendar-toolbar"><b>Setembro 2026</b>${btn('Hoje','toast(\'Hoje selecionado.\')')}</div><div class="calendar-grid">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${Array.from({length:35},(_,i)=>{const d=i<24?i+1:i-24;return `<button class="cal-day ${i===9?'today':''} ${i>=24?'muted-day':''}" onclick="calendarDay(${d})"><b>${d}</b>${[14,16,20].includes(d)&&i<24?`<span>${d===14?'Banco de Dados':d===16?'Grupo de estudos':'Campanha'}</span>`:''}</button>`}).join('')}</div>`);}
function calendarDay(d){modal(`Agenda do dia ${d}/09`,`<div class="list-row"><div><b>${d===14?'Estudar Banco de Dados':d===16?'Grupo de estudos':d===20?'Semana do Bem-estar':'Sem compromisso principal'}</b><small>${d===14?'14:00 · 25 min':'Dia livre até o momento'}</small></div></div>${btn('Nova tarefa','primary','closeModal();openNewTask()')}`);}
function habits(){return `<div class="two-col">${card('Hábitos','Metas simples para acompanhar sem culpa.',`<div class="list">${data.habits.map((h,i)=>`<div class="list-row"><div class="row-main"><div class="habit-icon">${h[0].includes('água')?'💧':h[0].includes('Dormir')?'🌙':h[0].includes('Movimentar')?'🌿':'📚'}</div><div><b>${esc(h[0])}</b><small>${esc(h[1])} · ${esc(h[2])}</small></div></div><div class="habit-progress"><div class="progress"><span style="width:${h[3]}%"></span></div>${btn('Registrar',`markHabit(${i})`)}</div></div>`).join('')}</div><div class="card-footer">${btn('Novo hábito','openHabit()','primary')}</div>`)}${card('Constância','O progresso não precisa ser perfeito.','<div class="big-stat">12 <span>dias de prática</span></div>','soft-card')}</div>`;}
function openHabit(){modal('Novo hábito',`<form onsubmit="saveHabit(event)"><div class="form-grid"><div class="field full"><label>Nome</label><input name="title" required></div><div class="field"><label>Meta</label><input name="goal"></div><div class="field"><label>Frequência</label><select name="freq"><option>Diário</option><option>3x por semana</option><option>5x por semana</option></select></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function saveHabit(e){e.preventDefault();const f=new FormData(e.target);data.habits.push([f.get('title'),f.get('goal'),f.get('freq'),0]);save();closeModal();render();}
function markHabit(i){data.habits[i][3]=Math.min(100,data.habits[i][3]+5);save();render();toast('Hábito registrado.');}

function estudar(view='Visão geral'){return page('Estudar com equilíbrio','Foco, pausas e acompanhamento — sem excesso de informação.',tabsHtml(['Visão geral','Pomodoro','Modo Foco','Progresso'],view,'studyTab')+(view==='Visão geral'?studyHome():view==='Pomodoro'?pomodoro():view==='Modo Foco'?focus():progress()),'Estudos');}
function studyTab(v){go(v==='Visão geral'?'/estudar':v==='Pomodoro'?'/estudar/pomodoro':v==='Modo Foco'?'/estudar/foco':'/estudar/progresso');}
function studyHome(){return `<div class="two-col">${card('Foco de hoje','Uma sessão por vez.',pomoBlock())}${card('Seu progresso','Esta semana',`<div class="stats big"><div><b>6h20</b><span>tempo estudado</span></div><div><b>14</b><span>Pomodoros</span></div><div><b>82%</b><span>meta semanal</span></div></div><div class="chart">${[42,62,35,88,52,74,60].map((v,i)=>`<div><i style="height:${v}%"></i><small>${['S','T','Q','Q','S','S','D'][i]}</small></div>`).join('')}</div>`)} </div>`;}
function pomoBlock(){return `<div class="pomo-ring"><div><small>Pomodoro</small><strong>${fmt(state.timer)}</strong></div></div><div class="head-actions center">${btn(state.running?'Pausar':'Iniciar foco','toggleTimer()','primary')}${btn('Reiniciar','resetTimer()')}</div><div class="focus-tools"><button class="tool-chip" onclick="selectSound('Chuva suave')">🌧️ Chuva</button><button class="tool-chip" onclick="selectSound('Floresta')">🌲 Floresta</button><button class="tool-chip" onclick="selectSound('Café')">☕ Café</button><span class="sound-state">${state.sound}</span></div>`;}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function toggleTimer(){state.running=!state.running;clearInterval(state.interval);if(state.running)state.interval=setInterval(()=>{if(state.timer>0){state.timer--;render()}else resetTimer()},1000);render();}
function resetTimer(){clearInterval(state.interval);state.running=false;state.timer=1500;render();}
function selectSound(s){state.sound=s;toast('Som: '+s);render();}
function pomodoro(){return `<div class="two-col">${card('Pomodoro','25/5, 50/10 ou personalizado.',pomoBlock())}${card('Histórico recente','Sessões registradas localmente.','<div class="list-row"><div><b>Ontem · Banco de Dados</b><small>25 min · concluído</small></div><span class="pill">Concluído</span></div><div class="list-row"><div><b>Ontem · TCC</b><small>50 min · concluído</small></div><span class="pill">Concluído</span></div>')}</div>`;}
function focus(){return `<section class="card focus-screen"><div class="kicker">Modo Foco</div><h2>Banco de Dados</h2><div class="focus-time">${fmt(state.timer)}</div><p class="sub">Som: ${state.sound}</p><div class="head-actions center">${btn(state.running?'Pausar':'Iniciar foco','toggleTimer()','primary')}${btn('Encerrar sessão','resetTimer()')}</div><div class="focus-tip"><b>🌿</b><span>Seu desempenho não precisa ser perfeito para que a sessão tenha valor.</span></div></section>`;}
function progress(){return `<div class="stats-row"><div class="stat"><b>6h20</b><span>horas estudadas</span></div><div class="stat"><b>14</b><span>Pomodoros</span></div><div class="stat"><b>18</b><span>tarefas concluídas</span></div><div class="stat"><b>82%</b><span>meta semanal</span></div></div>${card('Evolução semanal','Observe o ritmo, não apenas o resultado.',`<div class="chart tall">${[38,55,47,75,58,92,68].map((v,i)=>`<div><i style="height:${v}%"></i><small>${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'][i]}</small></div>`).join('')}</div>`)}`;}

function bemEstar(view='Hoje'){return page('Cuide de você no seu ritmo','Perceber, respirar, refletir e encontrar apoio quando precisar.',tabsHtml(['Hoje','Diário','Autoconhecimento','Práticas','Apoio'],view,'wellTab')+(view==='Hoje'?wellToday():view==='Diário'?diary():view==='Autoconhecimento'?knowledge():view==='Práticas'?practices():support()),'Bem-estar');}
function wellTab(v){go(v==='Hoje'?'/bem-estar':v==='Diário'?'/bem-estar/diario':v==='Autoconhecimento'?'/bem-estar/autoconhecimento':v==='Práticas'?'/bem-estar/praticas':'/bem-estar/apoio');}
function wellToday(){return `<div class="two-col">${card('Como você está hoje','O registro é para autopercepção, não diagnóstico.',`<div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(x=>`<button class="mood ${state.mood===x[0]?'selected':''}" onclick="state.mood='${x[0]}';render()"><span>${x[0]}</span>${x[1]}</button>`).join('')}</div><div class="field"><label>O que influenciou seu dia?</label><textarea id="moodNote" rows="4"></textarea></div>${btn('Salvar check-in','saveMoodDetailed()','primary')}`)}${card('Recomendação de hoje','Uma sugestão, não uma cobrança.','<div class="recommend"><span>🌬️</span><div><b>Respiração</b><p>Um minuto de pausa antes da próxima atividade.</p>'+btn('Começar','openBreathing()')+'</div></div><div class="recommend"><span>📔</span><div><b>Escrever</b><p>Registre em uma frase como foi seu dia.</p>'+link('Abrir diário','/bem-estar/diario')+'</div></div>','soft-card')}</div>`;}
function saveMoodDetailed(){if(!state.mood)return toast('Escolha uma emoção primeiro.');data.checkins.unshift([state.mood,'Hoje','Rotina',$('#moodNote')?.value.trim()||'']);state.mood=null;save();render();toast('Check-in registrado.');}
function moodHistory(){modal('Histórico de humor',data.checkins.map(c=>`<div class="list-row"><div><b>${c[0]} · ${c[1]}</b><small>${esc(c[3])}</small></div><span class="pill">${c[2]}</span></div>`).join('')+btn('Fechar','closeModal()'));}
function diary(){return `<div class="two-col">${card('Diário pessoal','Escreva, registre e volte quando quiser.',`<div class="list">${data.diary.map((d,i)=>`<article class="diary-item"><div class="diary-meta"><span>${d[2]}</span><small>${d[1]}</small></div><div><b>${esc(d[0])}</b><p>${esc(d[3])}</p><div class="row-actions">${btn('Editar',`openDiary(${i})`)}${btn('Excluir',`deleteDiary(${i})`)}</div></div></article>`).join('')}</div>${btn('Novo registro','openDiary()','primary')}`)}${card('Privacidade','Um espaço pessoal dentro do Bloom.','<p class="sub">Registros pessoais ficam separados do vínculo institucional.</p>','soft-card')}</div>`;}
function openDiary(i=null){const d=i!==null?data.diary[i]:null;modal(d?'Editar registro':'Novo registro',`<form onsubmit="saveDiary(event,${i===null?-1:i})"><div class="field"><label>Título</label><input name="title" value="${esc(d?.[0]||'')}" required></div><div class="field"><label>Texto</label><textarea name="text" rows="7" required>${esc(d?.[3]||'')}</textarea></div><div class="field"><label>Anexo</label><input type="file" accept="image/*,audio/*"></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);}
function saveDiary(e,i){e.preventDefault();const f=new FormData(e.target);if(i<0)data.diary.unshift([f.get('title'),'Hoje',state.mood||'🌱',f.get('text')]);else data.diary[i]=[f.get('title'),data.diary[i][1],data.diary[i][2],f.get('text')];save();closeModal();render();}
function deleteDiary(i){data.diary.splice(i,1);save();render();toast('Registro excluído.');}
function knowledge(){return `<div class="two-col">${card('Autoconhecimento','Reflexões e questionários como convite à observação.',`<div class="reflection-list">${[['🌱','Meu ritmo de energia','8 perguntas'],['🧭','Como organizo meu tempo','10 perguntas'],['💭','O que me ajuda a estudar','6 perguntas']].map((x,i)=>`<div class="reflection"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div>${btn('Abrir',`quiz(${i})`)}</div>`).join('')}</div>`)}${card('Seus resultados','Apresentados como reflexão pessoal.','<div class="stats big"><div><b>3</b><span>testes concluídos</span></div><div><b>12</b><span>reflexões</span></div><div><b>76%</b><span>evolução</span></div></div><p class="sub">Não representa diagnóstico psicológico.</p>','soft-card')}</div>`;}
function quiz(i){const q=[['Meu ritmo de energia',['Ter uma primeira ação pequena','Ter tudo planejado','Fazer junto com alguém']],['Como organizo meu tempo',['Priorizar poucas coisas','Reorganizar os horários','Pedir apoio']],['O que me ajuda a estudar',['Silêncio','Som ambiente','Movimento ao redor']]][i];modal(q[0],'<p class="sub">Escolha a resposta que mais combina com você agora.</p><div class="answer-list">'+q[1].map(a=>`<button class="answer" onclick="closeModal();toast('Reflexão registrada.')">${a}</button>`).join('')+'</div>');}
function practices(){return `<div class="practice-grid">${[['🌬️','Respiração','1–3 min','Regule o ritmo da respiração.'],['🧘','Meditação','5 min','Uma pausa guiada para desacelerar.'],['⏸️','Pausa consciente','2 min','Saia da tela, alongue e volte com calma.'],['🌙','Relaxamento','8 min','Uma rotina curta para encerrar o dia.']].map(x=>`<article class="card practice"><span>${x[0]}</span><div><h2>${x[1]}</h2><small>${x[2]}</small><p class="sub">${x[3]}</p></div>${btn('Começar',`openPractice('${x[1]}')`)}</article>`).join('')}</div>`;}
function openPractice(n){modal(n,`<div class="practice-modal"><div class="practice-orb">🌿</div><h3>Vamos começar com calma.</h3><p class="sub">Este exercício é demonstrativo.</p>${btn('Iniciar','toast(\'Prática iniciada.\');closeModal()','primary')}</div>`);}
function openBreathing(){openPractice('Respiração');}
function support(){return `<div class="two-col">${card('Encontrar apoio','Serviços demonstrativos em um raio de referência.',`<div class="support-filters"><button class="filter active">Até 10 km</button><button class="filter">Até 25 km</button><button class="filter">Até 50 km</button></div><div class="list">${data.support.map((s,i)=>`<article class="service"><div class="service-icon">🤝</div><div class="service-body"><div class="service-top"><div><b>${s[0]}</b><small>${s[2]}</small></div><span class="pill">${s[1]}</span></div><p>${s[3]}</p><div class="service-meta"><span>★ ${s[4]}</span><span>${s[5]}</span></div><div class="row-actions">${btn('Detalhes',`service(${i})`)}${btn('Ligar',`toast('Ligação demonstrativa.')`)}${btn('WhatsApp',`toast('WhatsApp demonstrativo.')`)}</div></div></article>`).join('')}</div>`)}${card('Apoio da instituição','Solicite ajuda e acompanhe o status.',data.requests.map(r=>`<div class="support-request"><div>💚</div><div><b>${r[1]}</b><small>${r[0]} · ${r[2]}</small><p>${esc(r[4])}</p><span class="pill terracotta">${r[3]}</span></div></div>`).join('')+`<div class="card-footer">${btn('Solicitar apoio','supportRequest()','primary')}</div>`,'soft-card')}</div>`;}
function service(i){const s=data.support[i];modal(s[0],`<p>${s[2]}</p><p><b>Endereço:</b> ${s[3]}</p><p><b>Avaliação:</b> ★ ${s[4]}</p><p><b>Horário:</b> ${s[5]}</p><p><b>Telefone:</b> ${s[6]}</p><div class="head-actions">${btn('Mapa','toast(\'Mapa demonstrativo aberto.\')')}${btn('Ligar','toast(\'Ligação demonstrativa.\')')}${btn('WhatsApp','toast(\'WhatsApp demonstrativo.\')','primary')}</div>`);}
function supportRequest(){modal('Solicitar apoio',`<form onsubmit="saveSupport(event)"><div class="field"><label>Tipo</label><select name="type"><option>Orientação</option><option>Psicológico</option><option>Acadêmico</option><option>Coordenação</option></select></div><div class="field"><label>O que você precisa?</label><textarea name="summary" rows="5" required></textarea></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Enviar</button></div></form>`);}
function saveSupport(e){e.preventDefault();const f=new FormData(e.target);data.requests.unshift(['Hoje',f.get('type'),'Setor de acolhimento','Solicitada',f.get('summary')]);save();closeModal();render();toast('Solicitação enviada.');}

function instituicao(view='Visão geral'){return page('Sua instituição, mais perto','Informações acadêmicas e espaços de participação, sem poluir a navegação.',tabsHtml(['Visão geral','Agenda','Apoio','Comunidade','Comunicação'],view,'instTab')+(view==='Visão geral'?instHome():view==='Agenda'?instAgenda():view==='Apoio'?instSupport():view==='Comunidade'?communities():communication()),'Vida acadêmica');}
function instTab(v){const m={'Visão geral':'/instituicao','Agenda':'/instituicao/agenda','Apoio':'/instituicao/apoio','Comunidade':'/instituicao/comunidade','Comunicação':'/instituicao/comunicacao'};go(m[v]);}
function instHome(){return `<div class="two-col">${card(data.user.institution?'Instituição vinculada':'Nenhuma instituição vinculada','Você controla o vínculo e o que recebe.',`<div class="institution-head"><div class="institution-mark">🏫</div><div><h2>${esc(data.user.institution||'Vincule sua instituição')}</h2><p class="sub">${esc(data.user.course)} · ${esc(data.user.className)}</p></div></div>${btn(data.user.institution?'Gerenciar vínculo':'Vincular instituição',data.user.institution?'openUnlink()':'linkInstitution()','secondary')}`,'soft-card')}${card('Atalhos institucionais','Só o essencial para resolver as coisas.',`<div class="institution-shortcuts"><button onclick="go('/instituicao/agenda')">📅<b>Agenda acadêmica</b><span>Provas e atividades</span></button><button onclick="go('/instituicao/apoio')">🤝<b>Apoio e acolhimento</b><span>Solicitar ajuda</span></button><button onclick="go('/instituicao/comunidade')">💬<b>Comunidade</b><span>Grupos e participação</span></button><button onclick="go('/instituicao/comunicacao')">📣<b>Comunicação</b><span>Avisos e campanhas</span></button></div>`)} </div><div class="two-col compact-gap" style="margin-top:18px">${card('Participação','Feedback e segurança ficam dentro da área institucional.',`<div class="participation-grid"><button onclick="feedback()"><b>📝 Feedback</b><span>Avalie matérias, professores e carga.</span></button><button onclick="report()"><b>🛡️ Denúncia</b><span>Canal restrito para situações graves.</span></button></div>`)}${card('Encerrar integração','Sem uma seção extra só para isso.','<p class="sub">Novos avisos e eventos deixam de chegar. Seus registros pessoais continuam privados.</p>'+btn('Gerenciar vínculo','secondary','openUnlink()'))}</div>`;}
function linkInstitution(){modal('Vincular instituição',`<div class="field"><label>Código ou convite</label><input id="code" placeholder="Ex.: BLOOM-2026"></div><div class="link-preview"><b>Universidade Bloom</b><small>Exemplo demonstrativo</small></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button>${btn('Vincular','confirmLink()','primary')}</div>`);}
function confirmLink(){data.user.institution='Universidade Bloom';save();closeModal();render();toast('Instituição vinculada.');}
function openUnlink(){modal('Encerrar integração','<div class="notice-box"><b>Antes de confirmar</b><p>Novos avisos e eventos deixarão de chegar. Seus registros pessoais continuam separados.</p></div><div class="modal-actions">'+btn('Cancelar','closeModal()')+btn('Confirmar','unlink()','danger')+'</div>');}
function unlink(){data.user.institution='';save();closeModal();render();toast('Vínculo encerrado.');}
function instAgenda(){return `<div class="grid-3">${data.events.map((e,i)=>`<article class="event-card"><div><span class="pill">${e[0]}</span><h3>${esc(e[1])}</h3><p class="sub">${esc(e[2])}</p></div><div class="row-actions">${btn(e[4]?'Cancelar':'Participar',e[4]?`eventToggle(${i})`:`eventToggle(${i})`,e[4]?'secondary':'primary')}${btn(e[5]?'Lembrete ativo':'Lembrete',`eventReminder(${i})`)}${btn('Detalhes',`eventDetail(${i})`)}</div></article>`).join('')}</div>`;}
function eventToggle(i){data.events[i][4]=!data.events[i][4];save();render();toast(data.events[i][4]?'Participação confirmada.':'Participação cancelada.');}
function eventReminder(i){data.events[i][5]=!data.events[i][5];save();render();toast(data.events[i][5]?'Lembrete ativado.':'Lembrete desativado.');}
function eventDetail(i){const e=data.events[i];modal(e[1],`<p>${e[3]}</p><p><b>Quando:</b> ${e[0]}</p><p><b>Onde:</b> ${e[2]}</p><div class="field"><label>Pergunta anônima</label><textarea rows="4"></textarea></div>${btn('Enviar pergunta','toast(\'Pergunta anônima enviada.\');closeModal()','primary')}`);}
function instSupport(){return `<div class="two-col">${card('Apoio e acolhimento','Acompanhe uma solicitação sem expor detalhes.',data.requests.map(r=>`<div class="support-request"><div>💚</div><div><b>${r[1]}</b><small>${r[0]} · ${r[2]}</small><p>${esc(r[4])}</p><span class="pill terracotta">${r[3]}</span></div></div>`).join('')+btn('Solicitar ajuda','supportRequest()','primary'))}${card('Segurança','Recursos importantes em uma única área.',`<div class="participation-grid"><button onclick="feedback()"><b>📝 Feedback</b><span>Sugestões, elogios ou reclamações.</span></button><button onclick="report()"><b>🛡️ Denúncia</b><span>Relate situações graves.</span></button></div>`,'soft-card')}</div>`;}
function communities(){return `<div class="grid-3">${data.communities.map((c,i)=>`<article class="community-card"><div class="community-top"><div class="community-icon">${c[1]}</div><span class="pill">${c[3]} membros</span></div><h3>${esc(c[0])}</h3><p class="sub">${esc(c[2])}</p><div class="row-actions">${btn(c[4]?'Sair':'Entrar',`communityToggle(${i})`,c[4]?'secondary':'primary')}${c[4]?btn('Abrir',`openCommunity(${i})`):''}</div></article>`).join('')}</div>`;}
function communityToggle(i){data.communities[i][4]=!data.communities[i][4];data.communities[i][3]+=data.communities[i][4]?1:-1;save();render();}
function openCommunity(i){const c=data.communities[i];modal(c[0],`<p class="sub">${c[2]}</p><div class="post"><div class="post-meta"><b>Rafa</b><small>08:20</small></div><p>Alguém quer revisar React hoje?</p><div class="row-actions">${btn('♡ 4','toast(\'Curtida registrada.\')')}${btn('💬 2','showComments()')}</div></div><div class="modal-actions">${btn('Nova publicação','newPost('+i+')','primary')}${btn('Fechar','closeModal()')}</div>`);}
function newPost(i){modal('Nova publicação',`<div class="field"><label>Mensagem</label><textarea id="post" rows="5"></textarea></div>${btn('Publicar',`publish(${i})`,'primary')}`);}
function publish(){if(!$('#post')?.value.trim())return toast('Digite uma mensagem.');closeModal();toast('Publicação criada.');}
function showComments(){modal('Comentários','<div class="post"><b>Rafa</b><p>Alguém quer revisar React hoje?</p></div><div class="field"><label>Comentário</label><input id="comment"></div>'+btn('Comentar','closeModal()','primary'));}
function communication(){return `<div class="two-col">${card('Comunicação','Avisos, campanhas e conteúdos.',data.communications.map(c=>`<article class="communication"><span class="pill">${c[0]}</span><h3>${esc(c[1])}</h3><p class="sub">${esc(c[2])}</p><small>${c[3]}</small>${c[0]==='Campanha'?btn('Perguntar anonimamente','openAnonymousQuestion()'):''}</article>`).join(''))}${card('Feedback','Sua opinião também é participação.',`<p class="sub">Avalie matérias, professores, carga ou instituição.</p>${btn('Enviar feedback','feedback()','primary')}${btn('Nova denúncia','report()','danger')}`,'soft-card')}</div>`;}
function feedback(){modal('Enviar feedback',`<form onsubmit="saveFeedback(event)"><div class="form-grid"><div class="field"><label>Tipo</label><select name="type"><option>Sugestão</option><option>Elogio</option><option>Reclamação</option><option>Avaliação</option></select></div><div class="field"><label>Sobre</label><select name="target"><option>Matéria</option><option>Professor</option><option>Carga de atividades</option><option>Instituição</option></select></div><div class="field full"><label>Mensagem</label><textarea name="text" rows="5" required></textarea></div><div class="field"><label>Identificação</label><select><option>Identificado</option><option>Anônimo</option></select></div></div>${btn('Cancelar','closeModal()')}${btn('Enviar','saveFeedbackForm()','primary')}</form>`);}
function saveFeedbackForm(){data.feedback.unshift(['Hoje','Sugestão','Instituição','Recebido']);save();closeModal();toast('Feedback enviado.');}
function saveFeedback(e){e.preventDefault();saveFeedbackForm();}
function report(){modal('Nova denúncia',`<form onsubmit="saveReport(event)"><div class="form-grid"><div class="field"><label>Identificação</label><select name="anonymous"><option>Anônima</option><option>Quero me identificar</option></select></div><div class="field"><label>Tipo</label><select><option>Assédio</option><option>Violência</option><option>Discriminação</option><option>Outra situação grave</option></select></div><div class="field"><label>Data</label><input type="date"></div><div class="field"><label>Horário</label><input type="time"></div><div class="field full"><label>Local</label><input></div><div class="field full"><label>Relato</label><textarea name="text" rows="6" required></textarea></div><div class="field full"><label>Provas</label><input type="file" multiple accept="image/*,audio/*,video/*"></div></div>${btn('Cancelar','closeModal()')}${btn('Enviar denúncia','saveReportForm()','primary')}</form>`);}
function saveReportForm(){data.reports.unshift(['DEN-2026-'+String(data.reports.length+1).padStart(3,'0'),'Hoje','Nova denúncia','Anônima','Recebida']);save();closeModal();toast('Denúncia registrada.');}
function saveReport(e){e.preventDefault();saveReportForm();}
function openAnonymousQuestion(){modal('Pergunta anônima','<div class="field"><label>Sua pergunta</label><textarea rows="5"></textarea></div>'+btn('Enviar','closeModal();toast(\'Pergunta anônima enviada.\')','primary'));}

function notifications(){return page('Notificações','Lembretes úteis, sem criar uma seção separada para “Lembretes”.',`<div class="notice-summary"><b>${data.notices.filter(x=>!x[3]).length}</b><span>não lidas</span></div><div class="notification-list">${data.notices.map((n,i)=>`<article class="notification ${n[3]?'':'unread'}"><div class="notif-icon">${n[0]}</div><div><b>${esc(n[1])}</b><small>Hoje · ${n[2]}</small></div><button class="text-btn" onclick="readNotice(${i})">${n[3]?'Lida':'Marcar como lida'}</button></article>`).join('')}</div>${btn('Marcar todas como lidas','readAll()')}`,'Centro de notificações');}
function readNotice(i){data.notices[i][3]=true;save();render();}
function readAll(){data.notices.forEach(n=>n[3]=true);save();render();toast('Tudo marcado como lido.');}
function profile(){return page('Meu perfil','Seus dados e conquistas, sem excesso.',`<div class="profile-grid">${card('Ana Silva','Ciência da Computação',`<div class="big-avatar">AS</div><p>${esc(data.user.email)}</p><p>${esc(data.user.className)}</p>${btn('Editar perfil','profileEdit()')}`)}${card('Resumo','Informações essenciais.',`<div class="stats big"><div><b>15</b><span>dias de sequência</span></div><div><b>24</b><span>sessões de foco</span></div><div><b>8</b><span>conquistas</span></div></div>`)}</div>`,'Conta');}
function profileEdit(){modal('Editar perfil',`<form onsubmit="saveProfile(event)"><div class="form-grid"><div class="field"><label>Nome</label><input name="name" value="${esc(data.user.name)}"></div><div class="field"><label>Curso</label><input name="course" value="${esc(data.user.course)}"></div><div class="field"><label>E-mail</label><input name="email" value="${esc(data.user.email)}"></div><div class="field"><label>Turma</label><input name="className" value="${esc(data.user.className)}"></div></div>${btn('Cancelar','closeModal()')}${btn('Salvar','primary')}</form>`);}
function saveProfile(e){e.preventDefault();const f=new FormData(e.target);Object.assign(data.user,{name:f.get('name'),course:f.get('course'),email:f.get('email'),className:f.get('className')});save();closeModal();render();}
function settings(){return page('Configurações','Poucas opções, claramente separadas por finalidade.',`<div class="settings-grid">${card('Notificações','Escolha o que merece chegar até você.',setting('reminders','Tarefas, hábitos e compromissos')+setting('study','Estudos')+setting('wellbeing','Bem-estar')+setting('institution','Instituição'))}${card('Aparência','Tema e recomendações.',`<div class="setting-row"><div><b>Tema</b><small>Claro ou escuro.</small></div><select class="simple-select" onchange="setTheme(this.value)"><option value="light" ${state.theme==='light'?'selected':''}>Claro</option><option value="dark" ${state.theme==='dark'?'selected':''}>Escuro</option></select></div><div class="setting-row"><div><b>Recomendação na Home</b><small>Uma sugestão contextual.</small></div><button class="switch ${state.settings?.home?'on':''}" onclick="toggleHomeRec()"><span></span></button></div>`)}${card('Privacidade','Controle sobre seus dados locais.',`<div class="setting-row"><div><b>Registros pessoais</b><small>Diário e check-ins ficam separados do vínculo institucional.</small></div><span class="pill">Privado</span></div><div class="card-footer">${btn('Exportar dados','exportData()')}${btn('Limpar dados','clearData()','danger')}</div>`)}${card('Conta demonstrativa','Autenticação real não faz parte desta versão estática.','<p class="sub">O protótipo foi pensado para navegação e apresentação no GitHub Pages.</p>')}</div>`,'Conta');}
function setting(k,t){return `<div class="setting-row"><div><b>${t}</b><small>Ativar ou desativar esta categoria.</small></div><button class="switch ${state.settings?.[k]?'on':''}" onclick="toggleSetting('${k}')"><span></span></button></div>`;}
function toggleSetting(k){state.settings=state.settings||{};state.settings[k]=!state.settings[k];save();render();}
function toggleHomeRec(){state.settings=state.settings||{};state.settings.home=!state.settings.home;save();render();}
function setTheme(v){state.theme=v;localStorage.setItem('bloom-theme',v);document.documentElement.dataset.theme=v;render();}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='bloom-dados.json';a.click();toast('Arquivo preparado.');}
function clearData(){localStorage.removeItem('bloom-data');location.reload();}
function openSOS(){modal('SOS','<div class="notice-box"><b>Situação urgente?</b><p>Fluxo demonstrativo; não realiza chamadas reais.</p></div>'+btn('Acionar SOS','toast(\'SOS demonstrativo acionado.\');closeModal()','danger'));}

function render(){nav();let v=home();switch(path()){case'/organizar':v=organizar('Visão geral');break;case'/organizar/tarefas':v=organizar('Tarefas');break;case'/organizar/calendario':v=organizar('Calendário');break;case'/organizar/habitos':v=organizar('Hábitos');break;case'/organizar/ideias':v=organizar('Visão geral');break;case'/estudar':v=estudar('Visão geral');break;case'/estudar/pomodoro':v=estudar('Pomodoro');break;case'/estudar/foco':v=estudar('Modo Foco');break;case'/estudar/progresso':v=estudar('Progresso');break;case'/bem-estar':v=bemEstar('Hoje');break;case'/bem-estar/diario':v=bemEstar('Diário');break;case'/bem-estar/autoconhecimento':v=bemEstar('Autoconhecimento');break;case'/bem-estar/praticas':v=bemEstar('Práticas');break;case'/bem-estar/respiracao':v=bemEstar('Práticas');break;case'/bem-estar/apoio':v=bemEstar('Apoio');break;case'/instituicao':v=instituicao('Visão geral');break;case'/instituicao/agenda':v=instituicao('Agenda');break;case'/instituicao/apoio':v=instituicao('Apoio');break;case'/instituicao/comunidade':v=instituicao('Comunidade');break;case'/instituicao/comunicacao':v=instituicao('Comunicação');break;case'/notificacoes':v=notifications();break;case'/perfil':v=profile();break;case'/configuracoes':v=settings();break;}$('#app').innerHTML=v;}
window.addEventListener('hashchange',render);
$('#notificationButton')?.addEventListener('click',()=>go('/notificacoes'));
$('#profileMenu')?.addEventListener('click',()=>modal('Conta rápida','<div class="account-menu"><a href="#/perfil" onclick="closeModal()">👤 <b>Meu perfil</b></a><a href="#/configuracoes" onclick="closeModal()">⚙️ <b>Configurações</b></a></div>'));
$('#modalBackdrop')?.addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
render();
