const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];

const navItems = [
  ['/', 'Início'],
  ['/organizar', 'Organizar'],
  ['/estudar', 'Estudar'],
  ['/bem-estar', 'Bem-estar'],
  ['/instituicao', 'Instituição']
];

const seed = {
  user: { name:'Ana Silva', email:'ana@universidadebloom.edu.br', course:'Ciência da Computação', class:'4º semestre · Turma B', institution:'Universidade Bloom', avatar:'AS', mascot:'🦫' },
  tasks: [
    {id:1,title:'Estudar Banco de Dados',cat:'Estudos',due:'Hoje',priority:'Alta',done:false},
    {id:2,title:'Revisar introdução do TCC',cat:'TCC',due:'Amanhã',priority:'Média',done:false},
    {id:3,title:'Enviar relatório do grupo',cat:'Projeto',due:'Hoje',priority:'Alta',done:true},
    {id:4,title:'Separar material de aula',cat:'Organização',due:'Sexta',priority:'Baixa',done:false}
  ],
  habits: [
    {id:1,title:'Beber água',goal:'2 L por dia',freq:'Diário',progress:70,icon:'💧',checked:false},
    {id:2,title:'Dormir bem',goal:'8h por noite',freq:'Diário',progress:86,icon:'🌙',checked:false},
    {id:3,title:'Movimentar o corpo',goal:'30 min',freq:'5x por semana',progress:58,icon:'🌿',checked:false},
    {id:4,title:'Estudar com foco',goal:'2 sessões',freq:'Diário',progress:75,icon:'📚',checked:false}
  ],
  ideas: [
    {id:1,text:'Pesquisar referências para o TCC',kind:'Pensamento',archived:false},
    {id:2,text:'Testar sons de floresta no modo foco',kind:'Ideia',archived:false}
  ],
  diary: [
    {id:1,title:'Um dia mais leve',date:'Hoje',mood:'🙂',text:'Consegui organizar minha tarde e fiz uma pausa antes da reunião.'},
    {id:2,title:'Reflexão',date:'Ontem',mood:'😌',text:'Percebi que estudar em blocos menores me ajuda a começar.'}
  ],
  checkins: [
    {id:1,date:'Hoje',mood:'🙂',factors:['Estudos'],note:'Dia organizado até aqui.'},
    {id:2,date:'Ontem',mood:'😐',factors:['Sono'],note:'Preciso desacelerar no fim do dia.'}
  ],
  notifications: [
    {id:1,icon:'📚',title:'Seu foco de hoje está esperando por você.',time:'Hoje, 08:42',kind:'Estudo',read:false},
    {id:2,icon:'🗓️',title:'Você tem 3 compromissos hoje.',time:'Hoje, 07:55',kind:'Agenda',read:false},
    {id:3,icon:'🌿',title:'Que tal fazer seu check-in emocional?',time:'Ontem, 20:10',kind:'Bem-estar',read:true},
    {id:4,icon:'🏫',title:'Novo evento disponível na instituição.',time:'Ontem, 16:20',kind:'Instituição',read:true}
  ],
  events: [
    {id:1,date:'14/09',title:'Workshop de Projetos',where:'Auditório principal',type:'Instituição',details:'Encontro sobre projetos acadêmicos e oportunidades.'},
    {id:2,date:'16/09',title:'Grupo de estudos — Banco de Dados',where:'Biblioteca',type:'Acadêmico',details:'Revisão colaborativa para a próxima avaliação.'},
    {id:3,date:'20/09',title:'Campanha Semana do Bem-estar',where:'Espaço de convivência',type:'Bem-estar',details:'Atividades opcionais de cuidado e integração.'}
  ],
  supportServices: [
    {id:1,name:'CAPS / Atendimento municipal',distance:'2,8 km',category:'Atendimento em saúde mental',address:'Rua das Flores, 120 · Centro',rating:'4,8',hours:'Seg–Sex · 08:00–18:00',phone:'(11) 4000-0101'},
    {id:2,name:'Centro de acolhimento estudantil',distance:'4,1 km',category:'Apoio psicológico e orientação',address:'Av. da Universidade, 450',rating:'4,9',hours:'Seg–Sex · 09:00–19:00',phone:'(11) 4000-0202'},
    {id:3,name:'Clínica-escola universitária',distance:'7,4 km',category:'Atendimento acadêmico',address:'Rua do Campus, 75',rating:'4,7',hours:'Seg–Sáb · 08:00–16:00',phone:'(11) 4000-0303'}
  ],
  communities: [
    {id:1,name:'Programação',icon:'👩‍💻',desc:'Grupo de estudo para programação web',members:18,joined:true,posts:[{author:'Rafa',text:'Alguém quer revisar React hoje?',time:'08:20',likes:4,comments:2}]},
    {id:2,name:'Vestibular',icon:'🎓',desc:'Dicas e apoio para provas',members:34,joined:false,posts:[]},
    {id:3,name:'Hobbies criativos',icon:'🎨',desc:'Trocas sobre desenho, música e projetos',members:12,joined:false,posts:[]},
    {id:4,name:'Banco de Dados',icon:'📚',desc:'Revisões para avaliações',members:26,joined:false,posts:[]},
    {id:5,name:'Dificuldades acadêmicas',icon:'🗣️',desc:'Espaço para conversar e compartilhar estratégias',members:21,joined:false,posts:[]},
    {id:6,name:'Bem-estar',icon:'🌱',desc:'Pausas e hábitos saudáveis',members:16,joined:false,posts:[]}
  ],
  supportRequests:[{id:1,date:'27/08',type:'Orientação',person:'Setor de acolhimento',status:'Em análise',summary:'Gostaria de conversar sobre organização e sobrecarga acadêmica.'}],
  reports:[{id:1,code:'DEN-2026-001',date:'25/08',title:'Situação no ambiente escolar',anonymous:true,status:'Em análise'}],
  feedback:[{id:1,date:'22/08',type:'Sugestão',target:'Carga de atividades',status:'Recebido'}],
  communications:[
    {id:1,type:'Comunicado',title:'Novo período de inscrições para monitoria',body:'As inscrições estão abertas até sexta-feira.',date:'Hoje'},
    {id:2,type:'Campanha',title:'Semana do Bem-estar',body:'Atividades opcionais de cuidado, pausa e convivência.',date:'Ontem'},
    {id:3,type:'Conteúdo',title:'Biblioteca com horários especiais',body:'Consulte os novos horários durante o período de avaliações.',date:'20/08'}
  ]
};

const state = {
  data: structuredClone(seed),
  mood:null,
  route:'/ ',
  orgTab:'Visão geral',
  studyTab:'Visão geral',
  wellTab:'Visão geral',
  instTab:'Visão geral',
  taskFilter:'Todas',
  noticeFilter:'Todas',
  sound:null,
  timer:{seconds:25*60,running:false,mode:'25/5',interval:null},
  theme:localStorage.getItem('bloom-theme')||'light',
  settings:Object.assign({reminders:true,study:true,wellbeing:true,institution:true,autoPause:false,compact:false}, JSON.parse(localStorage.getItem('bloom-settings')||'{}'))
};

function saveLocal(){
  localStorage.setItem('bloom-data', JSON.stringify(state.data));
  localStorage.setItem('bloom-settings', JSON.stringify(state.settings));
}
function loadLocal(){
  try{const d=localStorage.getItem('bloom-data');if(d)state.data=Object.assign(state.data,JSON.parse(d));}catch(e){}
}
loadLocal();

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function route(){return decodeURIComponent(location.hash.replace(/^#/,'')||'/').split('?')[0]||'/'}
function go(r){location.hash=r}
function setTheme(){
  const dark=state.theme==='dark';
  document.documentElement.dataset.theme=dark?'dark':'light';
}
function icon(i,label){return `<span aria-hidden="true">${i}</span><span>${label}</span>`}
function btn(t,cls='secondary',onclick=''){return `<button class="btn ${cls}" ${onclick?`onclick="${onclick}"`:''}>${t}</button>`}
function linkBtn(t,r,cls='secondary'){return `<a class="btn ${cls}" href="#${r}">${t}</a>`}
function pageHead(eyebrow,title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p></div><div class="head-actions">${actions}</div></div>`}
function tabs(items,current,handler){return `<div class="tabs">${items.map(t=>`<button class="tab ${current===t?'active':''}" onclick="${handler}('${t}')">${t}</button>`).join('')}</div>`}
function cardTitle(title,desc='',right=''){return `<div class="card-title"><div><h2>${title}</h2>${desc?`<div class="sub">${desc}</div>`:''}</div>${right}</div>`}
function shell(content){return `<div class="container">${content}</div>`}

function navbar(){
  $('#navLinks').innerHTML=navItems.map(([r,l])=>`<a href="#${r}" class="${route()===r||(r!=='/'&&route().startsWith(r))?'active':''}">${l}</a>`).join('');
}

function home(){
  const c=state.data.checkins[0];
  return shell(pageHead('Seu espaço de cuidado','Bom dia, Ana! 🌱','Que bom te ver por aqui. Vamos cuidar de você hoje?')+`
  <div class="grid-2">
    <section class="card"><div class="card-title"><div><h2>Como você está hoje?</h2><div class="sub">Um check-in rápido para começar o dia se percebendo.</div></div><span class="big-icon">♡</span></div>
      <div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(([i,t])=>`<button class="mood ${c?.mood===t||state.mood===t?'selected':''}" onclick="selectMood('${t}')"><span>${i}</span>${t}</button>`).join('')}</div>
      <div class="head-actions">${btn('Fazer check-in','primary','saveMood()')}${btn('Ver histórico','secondary','openMoodHistory()')}</div>
    </section>
    <section class="card soft bloom-card"><div class="eyebrow">Momento Bloom</div><div class="quote">Respire fundo.<br>Um passo de cada vez também te leva longe.</div>${btn('Respirar agora','primary','openBreathing()')}<div class="bloom-art">🌿</div></section>
  </div>
  <div class="grid-2" style="margin-top:20px">
    <section class="card">${cardTitle('Meu dia','Próximos compromissos')}<div class="events"><div class="event"><span class="event-time">14:00</span><div><b>Estudar Banco de Dados</b><small>Biblioteca · 25 min de foco</small></div></div><div class="event"><span class="event-time">17:30</span><div><b>Trabalho em grupo</b><small>Projeto Bloom</small></div></div><div class="event"><span class="event-time">20:00</span><div><b>Entregar relatório do TCC</b><small>Prazo hoje</small></div></div></div><div style="margin-top:15px">${linkBtn('Ver agenda','/organizar/calendario')}</div></section>
    <section class="card">${cardTitle('Continue de onde parou','Banco de Dados · Pomodoro','<strong>80%</strong>')}<div class="progress" style="margin:20px 0 14px"><span style="width:80%"></span></div><div class="sub" style="margin-bottom:15px">Próxima sessão sugerida: 25 minutos de foco.</div>${linkBtn('Iniciar foco','/estudar/pomodoro','primary')}</section>
  </div>
  <div class="grid-2-eq" style="margin-top:20px"><section class="card">${cardTitle('Autoconhecimento','Descubra mais sobre você e acompanhe seu crescimento pessoal.','<span class="big-icon">🌱</span>')}<div class="grid-4" style="margin:18px 0"><div class="stat"><div class="n">4</div><div class="label">Reflexões</div></div><div class="stat"><div class="n">3</div><div class="label">Testes</div></div><div class="stat"><div class="n">12</div><div class="label">Registros</div></div><div class="stat"><div class="n">76%</div><div class="label">Evolução</div></div></div>${linkBtn('Explorar agora','/bem-estar/autoconhecimento','primary')}</section>
    <section class="card support">${cardTitle('Precisa de ajuda?','Você não precisa enfrentar tudo sozinho. Estamos aqui para apoiar.','<span class="big-icon">🤝</span>')}<div class="head-actions" style="margin-top:20px">${btn('SOS','primary','openSOS()')}${linkBtn('Encontrar apoio','/bem-estar/apoio')}</div></section></div>
  <section class="card" style="margin-top:20px">${cardTitle('Acesso rápido','Ferramentas para cuidar da rotina sem perder o equilíbrio.')}<div class="grid-4" style="margin-top:17px">${[['⏱️','Pomodoro','/estudar/pomodoro'],['🎯','Modo Foco','/estudar/foco'],['🎧','Sons','/estudar/sons'],['📔','Diário','/bem-estar/diario'],['💭','Ideias','/organizar/ideias'],['🌱','Hábitos','/organizar/habitos'],['🗓️','Calendário','/organizar/calendario'],['🔔','Notificações','/notificacoes']].map(x=>`<a class="quick-card" href="#${x[2]}">${x[0]} ${x[1]}<small>Acessar agora</small></a>`).join('')}</div></section>`);
}
function selectMood(m){state.mood=m;render();toast('Humor selecionado: '+m)}
function saveMood(){if(!state.mood)return toast('Escolha uma emoção antes de salvar.');state.data.checkins.unshift({id:Date.now(),date:'Hoje',mood:state.mood,factors:['Rotina'],note:''});state.mood=null;saveLocal();render();toast('Check-in registrado com carinho. 💚')}
function openMoodHistory(){openModal('Histórico emocional',`<p class="muted">Registros para autopercepção, sem diagnóstico.</p><div class="list">${state.data.checkins.slice(0,8).map(x=>`<div class="row"><div class="left"><div class="mini-icon">${x.mood}</div><div><b>${x.date}</b><div class="sub">${x.factors?.join(', ')||'Sem fatores'} · ${x.note||'Sem observação'}</div></div></div></div>`).join('')}</div>`)}

function organizar(){return shell(pageHead('Organização pessoal','Organizar','Planeje sua rotina com leveza, sem transformar produtividade em cobrança.',btn('Nova tarefa','primary','openTask()'))+tabs(['Visão geral','Tarefas','Calendário','Hábitos','Ideias','Lembretes'],state.orgTab,'setOrgTab')+(state.orgTab==='Visão geral'?organizeOverview():state.orgTab==='Tarefas'?tasks():state.orgTab==='Calendário'?calendar():state.orgTab==='Hábitos'?habits():state.orgTab==='Ideias'?ideas():reminders()));}
function setOrgTab(t){state.orgTab=t;render()}
function organizeOverview(){return `<div class="grid-3"><div class="stat"><div class="n">${state.data.tasks.filter(t=>!t.done).length}</div><div class="label">Tarefas pendentes</div></div><div class="stat"><div class="n">4</div><div class="label">Hábitos ativos</div><div class="trend">+12% nesta semana</div></div><div class="stat"><div class="n">3</div><div class="label">Compromissos</div><div class="trend">Próximo às 14:00</div></div></div><div class="grid-2" style="margin-top:20px"><section class="card">${cardTitle('Hoje','O que merece sua atenção agora')}${state.data.tasks.slice(0,4).map(taskRow).join('')}</section><section class="card">${cardTitle('Próximos compromissos','Sem abrir o calendário inteiro')}<div class="timeline" style="margin-top:17px">${[['14:00','Estudar Banco de Dados','25 min de foco'],['17:30','Trabalho em grupo','Projeto Bloom'],['20:00','Entrega do relatório','Prazo hoje']].map(x=>`<div class="timeline-item"><div class="timeline-time">${x[0]}</div><div class="timeline-line"></div><div class="timeline-content"><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}</div></section></div>`}
function taskRow(t){return `<div class="row"><div class="left"><button class="check-btn ${t.done?'done':''}" onclick="toggleTask(${t.id})">${t.done?'✓':'○'}</button><div><b class="${t.done?'strike':''}">${t.title}</b><div class="sub">${t.cat} · ${t.due}</div></div></div><div class="row-actions"><span class="tag ${t.priority==='Alta'?'red':t.priority==='Média'?'peach':'gray'}">${t.priority}</span><button class="btn ghost" onclick="openTask(${t.id})">Editar</button></div></div>`}
function tasks(){const arr=state.data.tasks.filter(t=>state.taskFilter==='Todas'||(state.taskFilter==='Pendentes'&&!t.done)||(state.taskFilter==='Concluídas'&&t.done));return `<section class="card">${cardTitle('Tarefas','Criar, editar, concluir e acompanhar atividades.',btn('Nova tarefa','primary','openTask()'))}<div class="tabs" style="margin-top:18px">${['Todas','Pendentes','Concluídas'].map(t=>`<button class="tab ${state.taskFilter===t?'active':''}" onclick="state.taskFilter='${t}';render()">${t}</button>`).join('')}</div><div class="list">${arr.map(taskRow).join('')||'<div class="empty">Nenhuma tarefa neste filtro.</div>'}</div></section>`}
function toggleTask(id){const t=state.data.tasks.find(x=>x.id===id);if(t)t.done=!t.done;saveLocal();render();toast(t.done?'Tarefa concluída. 🌱':'Tarefa reaberta.')}
function openTask(id=null){const t=id?state.data.tasks.find(x=>x.id===id):null;openModal(id?'Editar tarefa':'Nova tarefa',`<form onsubmit="saveTask(event,${id||'null'})"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" required value="${t?esc(t.title):''}" placeholder="Ex.: Revisar matéria de cálculo"></div><div class="field"><label>Categoria</label><select name="cat"><option ${t?.cat==='Estudos'?'selected':''}>Estudos</option><option ${t?.cat==='TCC'?'selected':''}>TCC</option><option ${t?.cat==='Projeto'?'selected':''}>Projeto</option><option ${t?.cat==='Pessoal'?'selected':''}>Pessoal</option></select></div><div class="field"><label>Prioridade</label><select name="priority"><option ${t?.priority==='Alta'?'selected':''}>Alta</option><option ${t?.priority==='Média'?'selected':''}>Média</option><option ${t?.priority==='Baixa'?'selected':''}>Baixa</option></select></div><div class="field"><label>Prazo</label><input name="due" value="${t?esc(t.due):'Hoje'}"></div></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button>${t?`<button type="button" class="btn danger" onclick="deleteTask(${id})">Excluir</button>`:''}</div></form>`)}
function saveTask(e,id){e.preventDefault();const f=new FormData(e.target);const obj={title:f.get('title'),cat:f.get('cat'),priority:f.get('priority'),due:f.get('due')};if(id){Object.assign(state.data.tasks.find(x=>x.id===id),obj)}else state.data.tasks.unshift({id:Date.now(),...obj,done:false});saveLocal();closeModal();state.orgTab='Tarefas';render();toast(id?'Tarefa atualizada.':'Tarefa adicionada.')}
function deleteTask(id){state.data.tasks=state.data.tasks.filter(t=>t.id!==id);saveLocal();closeModal();render();toast('Tarefa excluída.')}
function calendar(){const days=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];const nums=[31,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4];return `<section class="card"><div class="calendar-head"><div><h2>Setembro 2026</h2><div class="sub">Tarefas, provas, compromissos e eventos acadêmicos.</div></div><div class="head-actions">${btn('←','secondary','toast(\'Mês anterior demonstrativo\')')}${btn('Hoje','secondary','toast(\'Hoje selecionado\')')}${btn('→','secondary','toast(\'Próximo mês demonstrativo\')')}</div></div><div class="calendar-grid">${days.map(d=>`<div class="cal-cell cal-week">${d}</div>`).join('')}${nums.map((n,i)=>`<div class="cal-cell ${n===10?'today':''} ${i<2||i>31?'muted-day':''}"><div class="cal-day">${n}</div>${[7,14,16,20].includes(n)?`<span class="cal-chip">${n===7?'Banco de Dados':n===14?'TCC':n===16?'Grupo': 'Entrega'}</span>`:''}${n===17?`<span class="cal-chip peach">Trabalho</span>`:''}</div>`).join('')}</div><div class="card soft" style="margin-top:17px;box-shadow:none"><b>Integração:</b><span class="sub"> tarefas com prazo e eventos institucionais podem aparecer juntos nesta agenda.</span></div></section>`}
function habits(){return `<div class="grid-2"><section class="card">${cardTitle('Hábitos','Defina meta, frequência e registre sem culpa.',btn('Novo hábito','primary','openHabit()'))}<div class="list">${state.data.habits.map(h=>`<div class="row"><div class="left"><button class="check-btn ${h.checked?'done':''}" onclick="toggleHabit(${h.id})">${h.checked?'✓':'○'}</button><div><b>${h.icon} ${h.title}</b><div class="sub">${h.goal} · ${h.freq}</div></div></div><div style="width:155px"><div class="sub" style="text-align:right;margin-bottom:5px">${h.progress}%</div><div class="progress"><span style="width:${h.progress}%"></span></div></div></div>`).join('')}</div></section><section class="card soft"><div class="eyebrow">Histórico</div><h2 style="margin:8px 0">12 dias de pequenas conquistas</h2><p class="muted">A consistência importa mais do que uma sequência perfeita.</p><div class="grid-2-eq" style="margin-top:18px"><div class="stat"><div class="n">73%</div><div class="label">meta geral</div></div><div class="stat"><div class="n">4</div><div class="label">hábitos ativos</div></div></div></section></div>`}
function toggleHabit(id){const h=state.data.habits.find(x=>x.id===id);if(h){h.checked=!h.checked;h.progress=Math.min(100,h.progress+(h.checked?5:-5))}saveLocal();render();toast(h.checked?'Hábito registrado.':'Registro desfeito.')}
function openHabit(){openModal('Novo hábito',`<form onsubmit="e=>e.preventDefault()"><div class="form-grid"><div class="field full"><label>Nome</label><input placeholder="Ex.: Caminhar 20 minutos"></div><div class="field"><label>Meta</label><input placeholder="20 min"></div><div class="field"><label>Frequência</label><select><option>Diário</option><option>3x por semana</option><option>5x por semana</option></select></div></div><div class="modal-actions"><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button><button class="btn primary" type="button" onclick="closeModal();toast('Novo hábito salvo no protótipo.')">Salvar</button></div></form>`) }
function ideas(){return `<div class="grid-2"><section class="card">${cardTitle('Caixa de ideias','Capture pensamentos agora e organize depois.',btn('Nova ideia','primary','openIdea()'))}<div class="list">${state.data.ideas.filter(i=>!i.archived).map(i=>`<div class="notice" style="margin-top:10px"><div class="mini-icon peach">💭</div><div class="n-body"><b>${esc(i.text)}</b><small>${i.kind} · captura rápida</small></div><div class="row-actions"><button class="btn ghost" onclick="ideaToTask(${i.id})">Virar tarefa</button><button class="btn ghost" onclick="archiveIdea(${i.id})">Arquivar</button></div></div>`).join('')}</div></section><section class="card peach"><div class="eyebrow">Lembrete gentil</div><h2 style="margin:8px 0">Nem toda ideia precisa virar tarefa.</h2><p class="muted">A Caixa de Ideias é um espaço de captura rápida, diferente de uma atividade organizada com prazo e status.</p><div class="head-actions">${btn('Criar por áudio','secondary','toast(\'Gravação de áudio simulada iniciada.\')')}${btn('Ver arquivadas','secondary','showArchivedIdeas()')}</div></section></div>`}
function openIdea(){openModal('Nova ideia',`<div class="field"><label>Texto</label><textarea id="ideaText" rows="5" placeholder="Escreva uma ideia, pensamento ou lembrete..."></textarea></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveIdea()">Salvar ideia</button></div>`)}
function saveIdea(){const t=$('#ideaText').value.trim();if(!t)return toast('Escreva uma ideia primeiro.');state.data.ideas.unshift({id:Date.now(),text:t,kind:'Ideia',archived:false});saveLocal();closeModal();render();toast('Ideia salva.')}
function archiveIdea(id){const i=state.data.ideas.find(x=>x.id===id);if(i)i.archived=true;saveLocal();render();toast('Ideia arquivada.')}
function ideaToTask(id){const i=state.data.ideas.find(x=>x.id===id);if(!i)return;state.data.tasks.unshift({id:Date.now(),title:i.text,cat:'Ideia convertida',due:'Hoje',priority:'Média',done:false});i.archived=true;saveLocal();render();toast('Ideia transformada em tarefa.')}
function showArchivedIdeas(){const arr=state.data.ideas.filter(i=>i.archived);openModal('Ideias arquivadas',arr.length?arr.map(i=>`<div class="row"><div><b>${esc(i.text)}</b><div class="sub">Arquivada</div></div><button class="btn ghost" onclick="restoreIdea(${i.id})">Restaurar</button></div>`).join(''):'<div class="empty">Nenhuma ideia arquivada.</div>')}
function restoreIdea(id){const i=state.data.ideas.find(x=>x.id===id);if(i)i.archived=false;saveLocal();closeModal();render();toast('Ideia restaurada.')}
function reminders(){return `<div class="grid-2"><section class="card">${cardTitle('Notificações e lembretes','Ative ou desative por categoria.')} ${['reminders','study','wellbeing','institution'].map((k,i)=>{const labels=['Tarefas, hábitos e compromissos','Estudos','Check-ins e bem-estar','Eventos e avisos da instituição'];return settingSwitch(k,labels[i],'Receber lembretes desta categoria.')}).join('')} </section><section class="card soft"><div class="eyebrow">Sugestão</div><h2 style="margin:8px 0">Seu ritmo importa.</h2><p class="muted">Lembretes devem apoiar sua rotina, não gerar culpa. Você pode ajustar tudo em Configurações.</p>${linkBtn('Abrir configurações','/configuracoes')}</section></div>`}

function estudar(){return shell(pageHead('Foco e aprendizado','Estudar com equilíbrio','Encontre foco, organização e motivação para aprender melhor.',linkBtn('Iniciar Pomodoro','/estudar/pomodoro','primary'))+tabs(['Visão geral','Plano de estudos','Disciplinas','Materiais','Desempenho'],state.studyTab,'setStudyTab')+(state.studyTab==='Visão geral'?studyOverview():state.studyTab==='Plano de estudos'?studyPlan():state.studyTab==='Disciplinas'?subjects():state.studyTab==='Materiais'?materials():performance()));}
function setStudyTab(t){state.studyTab=t;render()}
function studyOverview(){return `<div class="grid-2"><section class="card pomo"><div class="eyebrow">Foco de hoje</div><div class="pomo-ring"><div class="inside"><div class="sub">Pomodoro</div><div class="pomo-display">${formatTime(state.timer.seconds)}</div></div></div><div class="sub">${state.timer.running?'Sessão em andamento':'Pronto para começar'}</div><div class="head-actions" style="justify-content:center;margin-top:17px">${btn(state.timer.running?'Pausar':'Iniciar foco','primary','toggleTimer()')}${btn('Reiniciar','secondary','resetTimer()')}</div><div class="head-actions" style="justify-content:center;margin-top:14px"><button class="tab ${state.timer.mode==='25/5'?'active':''}" onclick="setTimerMode('25/5')">25/5</button><button class="tab ${state.timer.mode==='50/10'?'active':''}" onclick="setTimerMode('50/10')">50/10</button><button class="tab ${state.timer.mode==='custom'?'active':''}" onclick="setTimerMode('custom')">Personalizado</button></div></section><section class="card">${cardTitle('Seu progresso','Esta semana','<span class="big-icon">🌱</span>')}<div class="grid-2-eq" style="margin-top:18px"><div class="stat"><div class="n">6h20</div><div class="label">tempo estudado</div></div><div class="stat"><div class="n">14</div><div class="label">Pomodoros</div></div><div class="stat"><div class="n">18</div><div class="label">tarefas concluídas</div></div><div class="stat"><div class="n">82%</div><div class="label">meta semanal</div></div></div><div class="chart">${[42,62,35,88,52,74,60].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><small>${['S','T','Q','Q','S','S','D'][i]}</small></div>`).join('')}</div></section></div><div class="grid-3" style="margin-top:20px">${[['🎯','Modo Foco','Reduza distrações.','/estudar/foco'],['🎧','Sons ambientes','Crie seu ambiente de foco.','/estudar/sons'],['📈','Progresso','Veja sua evolução.','/estudar/progresso']].map(x=>`<a class="card" href="#${x[3]}"><div class="mini-icon">${x[0]}</div><h3 style="margin-top:14px">${x[1]}</h3><p class="sub">${x[2]}</p></a>`).join('')}</div>`}
function studyPlan(){return `<div class="grid-2"><section class="card">${cardTitle('Plano de estudos','Blocos planejados para os próximos dias.')} ${[['Banco de Dados','Hoje · 14:00','25 min'],['Engenharia de Software','Hoje · 16:00','50 min'],['TCC — Revisão','Amanhã · 10:00','50 min'],['Programação Web','Sexta · 14:00','25 min']].map(x=>`<div class="row"><div class="left"><div class="mini-icon">📚</div><div><b>${x[0]}</b><div class="sub">${x[1]} · ${x[2]}</div></div></div><span class="tag">Planejado</span></div>`).join('')}</section><section class="card soft"><div class="eyebrow">Sugestão</div><h2 style="margin:8px 0">Menos blocos, mais presença.</h2><p class="muted">Concentre duas sessões de foco e deixe espaço para pausas reais.</p></section></div>`}
function subjects(){return `<div class="grid-3">${[['Banco de Dados','72%','4 sessões'],['Engenharia de Software','61%','3 sessões'],['Programação Web','88%','6 sessões'],['Projeto Integrador','54%','2 sessões'],['Matemática Discreta','67%','3 sessões'],['TCC','40%','2 sessões']].map(x=>`<section class="card"><div class="card-title"><h3>${x[0]}</h3><strong>${x[1]}</strong></div><div class="progress" style="margin:14px 0"><span style="width:${x[1]}"></span></div><div class="sub">${x[2]} nesta semana</div></section>`).join('')}</div>`}
function materials(){return `<div class="grid-3">${[['📄','Apostila Banco de Dados','PDF · 12 páginas'],['📝','Resumo da aula 04','Anotações · atualizado hoje'],['🔗','Referências TCC','Links salvos · 8 itens'],['📑','Lista de exercícios','PDF · 20 questões'],['🎥','Aula gravada','Vídeo · 46 min'],['💡','Ideias de projeto','Notas rápidas · 6 itens']].map(x=>`<section class="card"><div class="mini-icon">${x[0]}</div><h3 style="margin-top:13px">${x[1]}</h3><p class="sub">${x[2]}</p>${btn('Abrir','secondary','toast(\'Recurso demonstrativo aberto.\')')}</section>`).join('')}</div>`}
function performance(){return `<div class="grid-2"><section class="card">${cardTitle('Desempenho','Evolução simples para orientar próximos passos.')}<div class="grid-2-eq" style="margin-top:17px"><div class="stat"><div class="n">6h20</div><div class="label">tempo estudado</div></div><div class="stat"><div class="n">14</div><div class="label">sessões</div></div></div><div class="chart">${[35,52,46,72,66,84,76,90].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><small>${i+1}</small></div>`).join('')}</div></section><section class="card peach"><div class="eyebrow">Reflexão da semana</div><h2 style="margin:8px 0">Qual ambiente te ajuda a entrar no foco?</h2><p class="muted">Use seu histórico para conhecer seus melhores ritmos.</p>${btn('Registrar reflexão','secondary','toast(\'Reflexão salva.\')')}</section></div>`}
function formatTime(s){const m=String(Math.floor(s/60)).padStart(2,'0');const sec=String(s%60).padStart(2,'0');return `${m}:${sec}`}
function toggleTimer(){state.timer.running=!state.timer.running;if(state.timer.running){clearInterval(state.timer.interval);state.timer.interval=setInterval(()=>{if(state.timer.seconds>0){state.timer.seconds--;render()}else{resetTimer();toast('Sessão concluída. Faça uma pausa. 🌿')}},1000)}else clearInterval(state.timer.interval);render();toast(state.timer.running?'Foco iniciado.':'Foco pausado.')}
function resetTimer(){clearInterval(state.timer.interval);state.timer.running=false;state.timer.seconds=state.timer.mode==='50/10'?3000:1500;render()}
function setTimerMode(m){state.timer.mode=m;resetTimer();toast(m==='custom'?'Personalizado selecionado.':'Modo '+m+' selecionado.')}
function pomodoroPage(){return shell(pageHead('Foco','Pomodoro','Uma sessão por vez, com pausas para respirar.',linkBtn('Voltar','/estudar'))+`<div class="grid-2"><section class="card pomo"><div class="pomo-ring"><div class="inside"><div class="eyebrow">Sessão atual</div><div class="pomo-display">${formatTime(state.timer.seconds)}</div></div></div><div class="head-actions" style="justify-content:center">${btn(state.timer.running?'Pausar':'Iniciar foco','primary','toggleTimer()')}${btn('Reiniciar','secondary','resetTimer()')}</div><div class="settings-inline"><span>Modo</span><select onchange="setTimerMode(this.value)"><option value="25/5">25/5</option><option value="50/10">50/10</option><option value="custom">Personalizado</option></select></div></section><section class="card">${cardTitle('Histórico da sessão','Registros locais deste protótipo.')}<div class="list"><div class="row"><div><b>Ontem · Banco de Dados</b><div class="sub">25 minutos · concluído</div></div><span class="tag">Concluído</span></div><div class="row"><div><b>Ontem · TCC</b><div class="sub">50 minutos · concluído</div></div><span class="tag">Concluído</span></div></div></section></div>`)}
function focusPage(){return shell(pageHead('Experiência minimalista','Modo Foco','Reduza distrações e fique presente na atividade atual.',linkBtn('Sair do foco','/estudar'))+`<section class="card focus-screen"><div class="eyebrow">Agora</div><h2>Banco de Dados</h2><div class="focus-time">${formatTime(state.timer.seconds)}</div><div class="sub">${state.sound?`Som: ${state.sound}`:'Sem som selecionado'}</div><div class="head-actions" style="justify-content:center;margin-top:20px">${btn(state.timer.running?'Pausar':'Iniciar foco','primary','toggleTimer()')}${btn('Encerrar sessão','secondary','resetTimer();toast(\'Sessão encerrada.\')')}</div><div class="focus-tip"><b>🌿 Lembrete</b><span>Seu desempenho não precisa ser perfeito para que a sessão tenha valor.</span></div></section>`)}
function soundsPage(){const sounds=[['rain','🌧️','Chuva suave','ambiente calmo'],['forest','🌲','Floresta','sons naturais'],['cafe','☕','Café','ruído aconchegante'],['waves','🌊','Ondas','ritmo constante'],['wind','🍃','Vento','brisa leve'],['white','〰️','Ruído branco','foco contínuo']];return shell(pageHead('Ambiente de foco','Sons ambientes','Biblioteca para estudo, relaxamento, meditação e sono.')+`<div class="grid-2"><section class="card"><div class="sound-grid">${sounds.map(s=>`<button class="sound ${state.sound===s[0]?'active':''}" onclick="selectSound('${s[0]}')"><span style="font-size:27px">${s[1]}</span><b>${s[2]}</b><small>${s[3]}</small></button>`).join('')}</div></section><section class="card soft">${cardTitle('Som atual',state.sound?`Reprodução simulada · ${state.sound}`:'Selecione um ambiente.','🎧')}<div class="setting-row"><div><b>Volume</b><div class="setting-desc">Nível do ambiente</div></div><input type="range" value="60" min="0" max="100"></div><div class="setting-row"><div><b>Duração</b><div class="setting-desc">Quanto tempo tocar</div></div><select><option>25 min</option><option>50 min</option><option>60 min</option><option>Contínuo</option></select></div><div class="head-actions">${btn(state.sound?'Pausar':'Ouvir','primary','toast(state.sound?\'Som pausado.\':\'Selecione um som.\')')}${btn('♡ Favoritar','secondary','toast(\'Favorito salvo.\')')}</div></section></div>`)}
function selectSound(s){state.sound=s;render();toast('Som selecionado. 🎧')}
function progressPage(){return shell(pageHead('Acompanhe sem se cobrar','Progresso nos estudos','Veja horas estudadas, sessões, metas e evolução.')+`<div class="grid-3"><div class="stat"><div class="n">6h20</div><div class="label">Horas esta semana</div><div class="trend">+1h10 vs. semana anterior</div></div><div class="stat"><div class="n">14</div><div class="label">Pomodoros</div><div class="trend">+3 nesta semana</div></div><div class="stat"><div class="n">82%</div><div class="label">Meta semanal</div><div class="trend">Dentro do esperado</div></div></div><section class="card" style="margin-top:20px">${cardTitle('Evolução semanal','Segunda a domingo')}<div class="chart tall">${[38,55,47,75,58,92,68].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><small>${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'][i]}</small></div>`).join('')}</div><div class="head-actions">${btn('Visão diária','secondary','toast(\'Visão diária aberta.\')')}${btn('Visão mensal','secondary','toast(\'Visão mensal aberta.\')')}</div></section>`)}

function bemEstar(){return shell(pageHead('Seu cuidado pessoal','Bem-estar','Explore o que combina com você hoje.')+tabs(['Visão geral','Humor','Diário','Autoconhecimento','Respiração','Práticas','Recomendações','Apoio'],state.wellTab,'setWellTab')+(state.wellTab==='Visão geral'?wellOverview():state.wellTab==='Humor'?moodPageFull():state.wellTab==='Diário'?diaryPage():state.wellTab==='Autoconhecimento'?selfKnowledge():state.wellTab==='Respiração'?breathPage():state.wellTab==='Práticas'?practices():state.wellTab==='Recomendações'?recommendations():supportPage()));}
function setWellTab(t){state.wellTab=t;render()}
function wellOverview(){return `<div class="grid-2"><section class="card soft">${cardTitle('Check-in de hoje','Seu registro é privado e serve para autopercepção.','🙂')}<div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(([i,t])=>`<button class="mood" onclick="selectMood('${t}')"><span>${i}</span>${t}</button>`).join('')}</div>${btn('Registrar check-in','primary','saveMood()')}</section><section class="card peach">${cardTitle('Momento Bloom','Faça uma pausa que realmente seja sua.','🌿')}<p class="muted">Respiração, silêncio, alongamento ou alguns minutos longe da tela.</p>${btn('Iniciar respiração','primary','openBreathing()')}</section></div><div class="grid-4" style="margin-top:20px">${[['🙂','Check-in','Perceba seu momento','Humor'],['📔','Diário','Registre pensamentos','Diário'],['🌱','Autoconhecimento','Reflita sobre você','Autoconhecimento'],['🤝','Encontrar apoio','Serviços próximos','Apoio'],['🌬️','Respiração','Pausas guiadas','Respiração'],['🧘','Práticas','Relaxamento e meditação','Práticas'],['💚','Recomendações','Sugestões do dia','Recomendações'],['🫧','Hábitos','Pequenas práticas','/organizar/habitos']].map(x=>`<button class="card quick-card" onclick="${x[3].startsWith('/')?`go('${x[3]}')`:`state.wellTab='${x[3]}';render()`}"><div class="mini-icon">${x[0]}</div><h3 style="margin-top:10px">${x[1]}</h3><p class="sub">${x[2]}</p></button>`).join('')}</div>`}
function moodPageFull(){return `<div class="grid-2"><section class="card"><h2>Check-in emocional</h2><p class="sub">Não é diagnóstico. É um registro pessoal para perceber seu momento.</p><div class="moods">${[['😄','Muito bem'],['🙂','Bem'],['😐','Normal'],['😔','Não muito bem'],['😣','Sobrecarregado']].map(([i,t])=>`<button class="mood ${state.mood===t?'selected':''}" onclick="selectMood('${t}')"><span>${i}</span>${t}</button>`).join('')}</div><div class="form-grid"><div class="field full"><label>O que influenciou seu dia?</label><div class="chips">${['Estudos','Sono','Relacionamentos','Rotina','Saúde','Descanso'].map(x=>`<button type="button" class="chip" onclick="this.classList.toggle('on')">${x}</button>`).join('')}</div></div><div class="field full"><label>Observação</label><textarea id="moodNote" rows="4" placeholder="Quer registrar algo?"></textarea></div></div><div style="margin-top:15px">${btn('Salvar check-in','primary','saveDetailedMood()')}</div></section><section class="card">${cardTitle('Histórico','Registros recentes')}<div class="list">${state.data.checkins.map(x=>`<div class="row"><div class="left"><div class="mini-icon">${x.mood}</div><div><b>${x.date}</b><div class="sub">${x.factors?.join(', ')||'Sem fatores'}${x.note?` · ${esc(x.note)}`:''}</div></div></div><button class="btn ghost" onclick="deleteCheckin(${x.id})">Excluir</button></div>`).join('')}</div></section></div>`}
function saveDetailedMood(){if(!state.mood)return toast('Selecione uma emoção.');const factors=$$('.chip.on').map(x=>x.textContent);const note=$('#moodNote').value;state.data.checkins.unshift({id:Date.now(),date:'Hoje',mood:state.mood,factors,note});state.mood=null;saveLocal();render();toast('Check-in salvo.')}
function deleteCheckin(id){state.data.checkins=state.data.checkins.filter(x=>x.id!==id);saveLocal();render();toast('Registro excluído.')}
function diaryPage(){return `<div class="grid-2"><section class="card">${cardTitle('Diário pessoal','Registre acontecimentos, pensamentos e sentimentos.',btn('Novo registro','primary','openDiary()'))}<div class="list">${state.data.diary.map(d=>`<div class="notice" style="margin-top:10px"><div class="mini-icon peach">${d.mood}</div><div class="n-body"><b>${esc(d.title)}</b><small>${d.date} · ${esc(d.text)}</small></div><div class="row-actions"><button class="btn ghost" onclick="openDiary(${d.id})">Editar</button><button class="btn ghost" onclick="deleteDiary(${d.id})">Excluir</button></div></div>`).join('')}</div></section><section class="card peach"><div class="eyebrow">Privacidade</div><h2 style="margin:8px 0">Este espaço é pessoal.</h2><p class="muted">No produto completo, diário, pensamentos, áudios e registros individuais devem ser tratados como privados.</p><div class="head-actions">${btn('Adicionar imagem','secondary','toast(\'Imagem simulada anexada.\')')}${btn('Gravar áudio','secondary','toast(\'Áudio simulado gravado.\')')}</div></section></div>`}
function openDiary(id=null){const d=id?state.data.diary.find(x=>x.id===id):null;openModal(id?'Editar registro':'Novo registro',`<div class="form-grid"><div class="field full"><label>Título</label><input id="dTitle" value="${d?esc(d.title):''}" placeholder="Como foi seu dia?"></div><div class="field"><label>Humor</label><select id="dMood"><option>🙂</option><option>😐</option><option>😔</option><option>😄</option></select></div><div class="field"><label>Data</label><input value="${d?d.date:'Hoje'}" disabled></div><div class="field full"><label>Texto</label><textarea id="dText" rows="6" placeholder="Escreva o que quiser...">${d?esc(d.text):''}</textarea></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveDiary(${id||'null'})">Salvar</button></div>`)}
function saveDiary(id){const title=$('#dTitle').value.trim(),text=$('#dText').value.trim(),mood=$('#dMood').value;if(!text)return toast('Escreva algo antes de salvar.');if(id)Object.assign(state.data.diary.find(x=>x.id===id),{title,text,mood});else state.data.diary.unshift({id:Date.now(),title:title||'Registro',date:'Hoje',mood,text});saveLocal();closeModal();render();toast('Registro salvo.')}
function deleteDiary(id){state.data.diary=state.data.diary.filter(x=>x.id!==id);saveLocal();render();toast('Registro excluído.')}
function selfKnowledge(){return `<div class="grid-2"><section class="card">${cardTitle('Questionários e reflexões','Convites à reflexão pessoal, nunca diagnóstico.')}<div class="list">${[['🌱','Como tenho cuidado da minha energia?','8 min'],['💭','O que me ajuda a estudar melhor?','5 min'],['🧭','Quais hábitos combinam com meu ritmo?','10 min'],['🪞','Como reajo quando minha rotina muda?','7 min']].map((x,i)=>`<div class="row"><div class="left"><div class="mini-icon">${x[0]}</div><div><b>${x[1]}</b><div class="sub">Reflexão · ${x[2]}</div></div></div><button class="btn secondary" onclick="startReflection(${i})">Começar</button></div>`).join('')}</div></section><section class="card soft">${cardTitle('Seu histórico','3 testes · 12 reflexões','🌱')}<div class="stat" style="margin-top:15px"><div class="n">76%</div><div class="label">evolução percebida</div></div><p class="muted" style="margin-top:16px">Os resultados mostram observações pessoais e não devem ser interpretados como diagnóstico psicológico.</p></section></div>`}
function startReflection(i){const qs=[['Como você tem cuidado da sua energia?',['Tenho respeitado pausas','Tenho priorizado o essencial','Ainda estou descobrindo']],['O que mais ajuda seu foco?',['Ambiente silencioso','Blocos curtos','Música ou sons']],['Quais hábitos combinam com você?',['Rotina fixa','Flexibilidade','Um pouco dos dois']],['Como reage a mudanças?',['Preciso de tempo','Adapto aos poucos','Gosto de experimentar']]][i];openModal('Reflexão Bloom',`<div class="eyebrow">Pergunta ${i+1} de 4</div><h3 style="margin:8px 0 18px">${qs[0]}</h3><div class="answer-list">${qs[1].map((a,j)=>`<button class="answer" onclick="finishReflection(${i},${j})">${a}</button>`).join('')}</div>`)}
function finishReflection(i,j){closeModal();showToast('Reflexão registrada. Seu resultado será usado apenas como observação pessoal.')}
function breathPage(){return `<section class="card soft breathing-screen"><div><div class="breath-orb">🌿</div><div class="eyebrow">Respiração</div><h2>Um minuto para voltar para você.</h2><p class="muted">Inspire por 4 segundos, segure por 2 e expire por 6.</p>${btn('Iniciar prática','primary','openBreathing()')}</div></section>`}
function practices(){return `<div class="grid-3">${[['🌬️','Respiração guiada','1–5 min','openBreathing()'],['🧘','Meditação breve','5–10 min','toast(\'Meditação iniciada no protótipo.\')'],['🌿','Relaxamento corporal','8 min','toast(\'Relaxamento iniciado no protótipo.\')'],['☕','Pausa consciente','3 min','toast(\'Pausa iniciada.\')'],['🫶','Desacelerar antes do estudo','4 min','toast(\'Prática para preparação do foco iniciada.\')'],['🌙','Desligar aos poucos','10 min','toast(\'Prática de descanso iniciada.\')']].map(x=>`<section class="card"><div class="mini-icon">${x[0]}</div><h3 style="margin-top:13px">${x[1]}</h3><p class="sub">${x[2]}</p>${btn('Começar','secondary',x[3])}</section>`).join('')}</div>`}
function recommendations(){return `<div class="grid-2"><section class="card">${cardTitle('Recomendação de hoje','Com base apenas em registros locais de demonstração.','💚')}<div class="recommend"><div class="mini-icon peach">🌿</div><div><h3>Uma pausa de 5 minutos</h3><p class="sub">Você marcou “sobrecarregado” recentemente. Que tal respirar antes da próxima tarefa?</p>${btn('Fazer agora','primary','openBreathing()')}</div></div><div class="recommend"><div class="mini-icon">📔</div><div><h3>Registrar como foi seu dia</h3><p class="sub">Um pequeno registro pode ajudar a perceber o que está funcionando.</p>${btn('Abrir diário','secondary','go(\'/bem-estar/diario\')')}</div></div></section><section class="card soft"><div class="eyebrow">Mensagem</div><h2 style="margin:8px 0">Você não precisa fazer tudo hoje para estar cuidando de si.</h2><p class="muted">Recomendações são sugestões de bem-estar, não avaliação clínica.</p></section></div>`}
function supportPage(){return `<section class="card">${cardTitle('Encontrar apoio','Exemplos fictícios para demonstrar a experiência; nenhum serviço real é consultado.','🤝')}<div class="location-strip"><b>Região de referência:</b> São Paulo · raio de até 50 km <button class="btn secondary" onclick="openLocation()">Alterar região</button></div><div class="grid-3" style="margin-top:16px">${state.data.supportServices.map(s=>`<article class="card service-card" style="box-shadow:none"><div class="institution-logo">🏡</div><div><div class="tag">${s.distance}</div><h3 style="margin:8px 0 4px">${esc(s.name)}</h3><p class="sub">${esc(s.category)}</p><div class="sub" style="margin-top:8px">${esc(s.address)}</div><div class="sub">⭐ ${s.rating} · ${s.hours}</div><div class="service-actions"><button class="btn secondary" onclick="showToast('Ligação demonstrativa.')">Ligar</button><button class="btn secondary" onclick="showToast('WhatsApp demonstrativo.')">WhatsApp</button><button class="btn secondary" onclick="showMap('${esc(s.name)}')">Mapa</button><button class="btn ghost" onclick="saveService(${s.id})">♡</button></div></div></article>`).join('')}</div></section>`}
function openLocation(){openModal('Região de busca',`<div class="field"><label>Cidade/região</label><input id="regionInput" value="São Paulo" placeholder="Digite uma cidade ou região"></div><p class="sub" style="margin-top:10px">Neste protótipo, a localização é informada manualmente e não é compartilhada automaticamente com uma instituição.</p><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="toast('Região atualizada.');closeModal()">Salvar</button></div>`)}
function showMap(name){window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(name),'_blank');}
function saveService(id){toast('Contato salvo na demonstração.')}

function instituicao(){return shell(pageHead('Vida acadêmica','Instituição','Conecte-se, participe e encontre apoio no ambiente acadêmico.',btn(state.data.user.institution?'Vinculada':'Vincular instituição',state.data.user.institution?'secondary':'primary','openInstitutionLink()'))+tabs(['Visão geral','Integração','Agenda acadêmica','Apoio','Comunidades','Feedback','Denúncias','Comunicação','Eventos e campanhas'],state.instTab,'setInstTab')+(state.instTab==='Visão geral'?institutionOverview():state.instTab==='Integração'?integrationPage():state.instTab==='Agenda acadêmica'?academicAgenda():state.instTab==='Apoio'?institutionSupport():state.instTab==='Comunidades'?communitiesPage():state.instTab==='Feedback'?feedbackPage():state.instTab==='Denúncias'?reportsPage():state.instTab==='Comunicação'?communicationPage():eventsCampaigns()));}
function setInstTab(t){state.instTab=t;render()}
function institutionOverview(){return `<div class="grid-2"><section class="card soft">${cardTitle(state.data.user.institution?'Instituição vinculada':'Nenhuma instituição vinculada','Você controla o que compartilha.','🏫')}<div style="display:flex;gap:15px;align-items:center;margin-top:12px"><div class="institution-logo">🏫</div><div><h2>${state.data.user.institution||'Vincule sua instituição'}</h2><div class="sub">${state.data.user.course} · ${state.data.user.class}</div></div></div><div class="grid-3" style="margin-top:17px"><div class="stat"><div class="n">3</div><div class="label">eventos</div></div><div class="stat"><div class="n">2</div><div class="label">novos avisos</div></div><div class="stat"><div class="n">6</div><div class="label">serviços</div></div></div></section><section class="card peach">${cardTitle('Destaque','Semana do Bem-estar','🌿')}<p class="muted">Confira as atividades e participe de forma opcional.</p>${btn('Ver campanha','primary','state.instTab=\'Eventos e campanhas\';render()')}</section></div><div class="grid-3" style="margin-top:20px">${[['📅','Agenda acadêmica','Provas, trabalhos e atividades.','Agenda acadêmica'],['🤝','Apoio e acolhimento','Solicite ajuda e acompanhe status.','Apoio'],['💬','Comunidades','Grupos de estudo e interesses.','Comunidades'],['📣','Comunicação','Avisos, campanhas e conteúdos.','Comunicação'],['📝','Feedback','Avalie matérias, professores e carga.','Feedback'],['🛡️','Denúncias','Canal restrito para situações graves.','Denúncias']].map(x=>`<button class="card" style="text-align:left" onclick="state.instTab='${x[3]}';render()"><div class="mini-icon">${x[0]}</div><h3 style="margin-top:13px">${x[1]}</h3><p class="sub">${x[2]}</p></button>`).join('')}</div>`}
function openInstitutionLink(){openModal('Vincular instituição',`<p class="muted">Use um convite ou código fornecido pela instituição. Aqui o processo é apenas demonstrativo.</p><div class="field"><label>Código de convite</label><input id="inviteCode" placeholder="Ex.: BLOOM-2026"></div><div style="margin-top:14px" class="card soft"><b>Exemplo encontrado</b><div class="sub" style="margin-top:4px">Universidade Bloom · Campinas, SP</div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="confirmInstitutionLink()">Vincular</button></div>`)}
function confirmInstitutionLink(){state.data.user.institution='Universidade Bloom';saveLocal();closeModal();render();toast('Instituição vinculada no protótipo.')}
function integrationPage(){return `<div class="grid-2"><section class="card">${cardTitle('Vínculo atual','Dados que a instituição pode disponibilizar ao estudante.','🏫')}<div class="list"><div class="row"><div><b>Instituição</b><div class="sub">Universidade Bloom</div></div></div><div class="row"><div><b>Curso / turma</b><div class="sub">${state.data.user.course} · ${state.data.user.class}</div></div></div><div class="row"><div><b>Vínculo</b><div class="sub">Ativo desde 18/08/2026</div></div><span class="tag">Ativo</span></div></div></section><section class="card peach">${cardTitle('Encerrar integração','Saiba o que acontece antes de confirmar.','↔')}<p class="muted">Ao encerrar, novos avisos e eventos da instituição deixam de chegar. Eventos já salvos permanecem na agenda pessoal até que você os remova.</p>${btn('Encerrar vínculo','danger','openUnlink()')}</section></div>`}
function openUnlink(){openModal('Encerrar vínculo',`<div class="card peach" style="box-shadow:none"><b>Antes de confirmar</b><ul><li>O Bloom deixará de receber novos dados institucionais.</li><li>Seus registros pessoais continuam privados.</li><li>Você poderá vincular novamente depois.</li></ul></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn danger" onclick="unlinkInstitution()">Confirmar encerramento</button></div>`)}
function unlinkInstitution(){state.data.user.institution='';saveLocal();closeModal();render();toast('Vínculo encerrado.')}
function academicAgenda(){return `<section class="card">${cardTitle('Agenda acadêmica','Eventos e atividades disponibilizados pela instituição.')}<div class="grid-3" style="margin-top:16px">${[['📘','Prova de Banco de Dados','14/09','Sala 204'],['📝','Entrega do projeto integrador','18/09','Portal do aluno'],['🏫','Palestra sobre carreira','20/09','Auditório']].map(x=>`<article class="card" style="box-shadow:none"><div class="mini-icon">${x[0]}</div><h3 style="margin-top:13px">${x[1]}</h3><p class="sub">${x[2]} · ${x[3]}</p>${btn('Adicionar ao calendário','secondary','toast(\'Evento acadêmico adicionado.\')')}</article>`).join('')}</div></section>`}
function institutionSupport(){return `<div class="grid-2"><section class="card">${cardTitle('Apoio e acolhimento','Solicite ajuda e acompanhe cada etapa.',btn('Solicitar ajuda','primary','openSupportRequest()'))}<div class="list">${state.data.supportRequests.map(r=>`<div class="notice ${r.status==='Concluído'?'':'unread'}" style="margin-top:10px"><div class="mini-icon">🤝</div><div class="n-body"><b>${r.type}</b><small>${r.date} · ${r.person}<br>${esc(r.summary)}</small><div class="support-track"><span class="done"></span><span class="done"></span><span class="${r.status==='Concluído'?'done':''}"></span><span></span></div></div><span class="tag peach">${r.status}</span></div>`).join('')}</div></section><section class="card soft"><div class="eyebrow">Fluxo demonstrativo</div><h2 style="margin:8px 0">Solicitada → Em análise → Encaminhada → Atendimento → Concluída</h2><p class="muted">O estudante consegue acompanhar o status sem expor detalhes pessoais na área pública.</p></section></div>`}
function openSupportRequest(){openModal('Solicitar apoio',`<div class="form-grid"><div class="field"><label>Tipo de apoio</label><select id="supportType"><option>Orientação</option><option>Psicológico</option><option>Coordenação</option><option>Acadêmico</option></select></div><div class="field"><label>Preferência</label><select><option>Online</option><option>Presencial</option><option>Tanto faz</option></select></div><div class="field full"><label>O que você gostaria de dizer?</label><textarea id="supportText" rows="5" placeholder="Você pode explicar o que está acontecendo."></textarea></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveSupportRequest()">Enviar solicitação</button></div>`)}
function saveSupportRequest(){const summary=$('#supportText').value.trim();if(!summary)return toast('Conte um pouco sobre o que você precisa.');state.data.supportRequests.unshift({id:Date.now(),date:'Hoje',type:$('#supportType').value,person:'Setor de acolhimento',status:'Solicitada',summary});saveLocal();closeModal();render();toast('Solicitação enviada.')}
function communitiesPage(){return `<div class="grid-3">${state.data.communities.map(c=>`<section class="card"><div class="card-title"><div><div class="mini-icon">${c.icon}</div><h3 style="margin-top:12px">${c.name}</h3></div><span class="tag">${c.members} membros</span></div><p class="sub">${c.desc}</p><div class="head-actions">${btn(c.joined?'Sair':'Entrar',c.joined?'secondary':'primary',`toggleCommunity(${c.id})`)}${c.joined?btn('Abrir grupo','secondary',`openCommunity(${c.id})`):''}</div></section>`).join('')}</div>`}
function toggleCommunity(id){const c=state.data.communities.find(x=>x.id===id);if(!c)return;c.joined=!c.joined;c.members+=c.joined?1:-1;saveLocal();render();toast(c.joined?'Você entrou na comunidade.':'Você saiu da comunidade.')}
function openCommunity(id){const c=state.data.communities.find(x=>x.id===id);if(!c)return;openModal(c.name,`<p class="muted">${c.desc}</p><div class="head-actions">${btn('Nova publicação','primary',`newPost(${id})`)}${btn('Sair do grupo','danger',`closeModal();toggleCommunity(${id})`)}</div><div class="list" style="margin-top:14px">${c.posts.length?c.posts.map((p,idx)=>`<div class="post"><div class="post-meta"><b>${esc(p.author)}</b><span>${p.time}</span></div><p>${esc(p.text)}</p><div class="post-actions"><button class="btn ghost" onclick="likePost(${id},${idx})">♡ ${p.likes}</button><button class="btn ghost" onclick="showComments(${id},${idx})">💬 ${p.comments}</button></div></div>`).join(''):'<div class="empty">Ainda não há publicações.</div>'}</div>`)}
function newPost(id){openModal('Nova publicação',`<div class="field"><label>Mensagem</label><textarea id="postText" rows="5" placeholder="Compartilhe algo com a comunidade..."></textarea></div><div class="modal-actions"><button class="btn secondary" onclick="openCommunity(${id})">Cancelar</button><button class="btn primary" onclick="savePost(${id})">Publicar</button></div>`)}
function savePost(id){const t=$('#postText').value.trim();if(!t)return toast('Digite uma mensagem.');const c=state.data.communities.find(x=>x.id===id);c.posts.unshift({author:'Ana Silva',text:t,time:'Agora',likes:0,comments:0});saveLocal();openCommunity(id);toast('Publicação criada.')}
function likePost(id,i){state.data.communities.find(c=>c.id===id).posts[i].likes++;saveLocal();openCommunity(id)}
function showComments(id,i){const p=state.data.communities.find(c=>c.id===id).posts[i];openModal('Comentários',`<div class="post"><b>${esc(p.author)}</b><p>${esc(p.text)}</p></div><div class="field" style="margin-top:12px"><label>Novo comentário</label><input id="commentText" placeholder="Escreva uma resposta"></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Fechar</button><button class="btn primary" onclick="addComment(${id},${i})">Comentar</button></div>`)}
function addComment(id,i){if(!$('#commentText').value.trim())return toast('Digite um comentário.');const p=state.data.communities.find(c=>c.id===id).posts[i];p.comments++;saveLocal();closeModal();toast('Comentário adicionado.')}
function feedbackPage(){return `<div class="grid-2"><section class="card">${cardTitle('Feedback institucional','Avalie matérias, professores, carga e envie sugestões.',btn('Novo feedback','primary','openFeedback()'))}<div class="list">${state.data.feedback.map(f=>`<div class="row"><div class="left"><div class="mini-icon">📝</div><div><b>${f.type} · ${f.target}</b><div class="sub">${f.date}</div></div></div><span class="tag">${f.status}</span></div>`).join('')}</div></section><section class="card soft"><div class="eyebrow">Importante</div><h2 style="margin:8px 0">Sua opinião ajuda a melhorar a experiência acadêmica.</h2><p class="muted">No sistema real, a instituição definiria quais feedbacks são identificados ou anônimos.</p></section></div>`}
function openFeedback(){openModal('Enviar feedback',`<div class="form-grid"><div class="field"><label>Tipo</label><select id="fbType"><option>Sugestão</option><option>Elogio</option><option>Reclamação</option><option>Avaliação</option></select></div><div class="field"><label>Sobre</label><select id="fbTarget"><option>Matéria</option><option>Professor</option><option>Carga de atividades</option><option>Instituição</option></select></div><div class="field full"><label>Mensagem</label><textarea id="fbText" rows="5" placeholder="Escreva seu feedback"></textarea></div><div class="field full"><label>Identificação</label><select><option>Identificado</option><option>Anônimo</option></select></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveFeedback()">Enviar</button></div>`)}
function saveFeedback(){const text=$('#fbText').value.trim();if(!text)return toast('Escreva seu feedback.');state.data.feedback.unshift({id:Date.now(),date:'Hoje',type:$('#fbType').value,target:$('#fbTarget').value,status:'Recebido'});saveLocal();closeModal();render();toast('Feedback enviado.')}
function reportsPage(){return `<div class="grid-2"><section class="card">${cardTitle('Canal de denúncias','Acesso restrito para situações graves.',btn('Nova denúncia','primary','openReport()'))}<div class="list">${state.data.reports.map(r=>`<div class="notice" style="margin-top:10px"><div class="mini-icon">🛡️</div><div class="n-body"><b>${r.code} · ${esc(r.title)}</b><small>${r.date} · ${r.anonymous?'Anônima':'Identificada'}</small></div><span class="tag peach">${r.status}</span></div>`).join('')}</div></section><section class="card peach"><div class="eyebrow">Privacidade</div><h2 style="margin:8px 0">Você decide se quer se identificar.</h2><p class="muted">O fluxo permite registrar data, hora, local e anexos. Neste protótipo, arquivos ficam apenas simulados.</p></section></div>`}
function openReport(){openModal('Nova denúncia',`<div class="form-grid"><div class="field"><label>Identificação</label><select id="reportAnon"><option value="true">Anônima</option><option value="false">Quero me identificar</option></select></div><div class="field"><label>Tipo</label><select><option>Assédio</option><option>Violência</option><option>Discriminação</option><option>Outra situação grave</option></select></div><div class="field"><label>Data</label><input type="date"></div><div class="field"><label>Horário aproximado</label><input type="time"></div><div class="field full"><label>Local</label><input placeholder="Ex.: corredor do bloco B"></div><div class="field full"><label>Relato</label><textarea id="reportText" rows="6" placeholder="Descreva o ocorrido."></textarea></div><div class="field full"><label>Provas (simuladas)</label><input type="file" accept="image/*,audio/*,video/*" multiple></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveReport()">Enviar denúncia</button></div>`)}
function saveReport(){const text=$('#reportText').value.trim();if(!text)return toast('Descreva o ocorrido.');state.data.reports.unshift({id:Date.now(),code:'DEN-2026-'+String(state.data.reports.length+2).padStart(3,'0'),date:'Hoje',title:'Novo relato registrado',anonymous:$('#reportAnon').value==='true',status:'Recebida'});saveLocal();closeModal();render();toast('Denúncia registrada de forma demonstrativa.')}
function communicationPage(){return `<section class="card">${cardTitle('Comunicação da instituição','Avisos, campanhas, publicações e materiais.')}<div class="grid-3" style="margin-top:16px">${state.data.communications.map(c=>`<article class="card event-card" style="box-shadow:none"><span class="tag ${c.type==='Campanha'?'peach':''}">${c.type}</span><h3 style="margin:12px 0 6px">${esc(c.title)}</h3><p class="sub">${esc(c.body)}</p><small class="muted">${c.date}</small><div class="head-actions" style="margin-top:12px">${btn('Ler conteúdo','secondary','openCommunication('+c.id+')')}${btn('Salvar','ghost','toast(\'Conteúdo salvo.\')')}</div></article>`).join('')}</div></section>`}
function openCommunication(id){const c=state.data.communications.find(x=>x.id===id);openModal(c.title,`<span class="tag">${c.type}</span><p style="margin-top:16px">${esc(c.body)}</p><div class="modal-actions"><button class="btn primary" onclick="closeModal()">Fechar</button></div>`)}
function eventsCampaigns(){return `<div class="grid-3">${state.data.events.map(e=>`<article class="card event-card"><div style="display:flex;justify-content:space-between;gap:14px"><div><span class="tag">${e.type}</span><h3 style="margin:10px 0 4px">${esc(e.title)}</h3><p class="sub">${esc(e.where)}</p></div><div class="event-date"><strong>${e.date.split('/')[0]}</strong><span>${e.date.split('/')[1]}</span></div></div><p class="sub">${esc(e.details)}</p><div class="head-actions"><button class="btn primary" onclick="participateEvent(${e.id})">Participar</button><button class="btn secondary" onclick="eventQuestion(${e.id})">Pergunta anônima</button><button class="btn ghost" onclick="toast('Evento adicionado ao calendário.')">＋ Agenda</button></div></article>`).join('')}</div>`}
function participateEvent(id){toast('Participação confirmada.');state.data.notifications.unshift({id:Date.now(),icon:'📅',title:'Participação confirmada em um evento.',time:'Agora',kind:'Instituição',read:false});saveLocal()}
function eventQuestion(id){const e=state.data.events.find(x=>x.id===id);openModal('Pergunta anônima',`<p class="muted">Evento: ${esc(e.title)}</p><div class="field"><label>Pergunta</label><textarea id="eventQ" rows="5" placeholder="Sua pergunta será enviada sem identificar você."></textarea></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="sendEventQuestion()">Enviar pergunta</button></div>`)}
function sendEventQuestion(){if(!$('#eventQ').value.trim())return toast('Digite uma pergunta.');closeModal();toast('Pergunta anônima enviada.')}

function notifications(){const f=state.data.notifications.filter(n=>state.noticeFilter==='Todas'||(state.noticeFilter==='Não lidas'&&!n.read)||n.kind===state.noticeFilter);return shell(pageHead('Tudo no seu tempo','Notificações','Lembretes, atividades e avisos importantes.')+tabs(['Todas','Não lidas','Estudo','Agenda','Bem-estar','Instituição'],state.noticeFilter,'setNoticeFilter')+`<div class="grid-2"><section>${f.map(n=>`<div class="notice ${n.read?'':'unread'}" style="margin-bottom:10px"><div class="mini-icon">${n.icon}</div><div class="n-body"><b>${esc(n.title)}</b><small>${n.time} · ${n.kind}</small></div><button class="btn ghost" onclick="markRead(${n.id})">${n.read?'✓':'Marcar'}</button></div>`).join('')||'<div class="card soft">Nada por aqui. 🌱</div>'}</section><aside class="card soft">${cardTitle('Resumo','Você controla os tipos de lembrete.','🔔')}<div class="stat" style="margin-top:15px"><div class="n">${state.data.notifications.filter(n=>!n.read).length}</div><div class="label">não lidas</div></div>${linkBtn('Configurar','/configuracoes')}</aside></div>`)}
function setNoticeFilter(t){state.noticeFilter=t;render()}
function markRead(id){const n=state.data.notifications.find(x=>x.id===id);if(n)n.read=true;saveLocal();render()}

function profile(){return shell(pageHead('Conta estudante','Meu perfil','Sua identidade, progresso e preferências.',linkBtn('Configurações','/configuracoes'))+`<div class="profile-hero"><aside class="card profile-side"><div class="big-avatar">AS</div><h2>${state.data.user.name}</h2><p class="sub">${state.data.user.course}</p><div class="tag">${state.data.user.class}</div><div style="margin-top:8px" class="tag">${state.data.user.institution||'Sem instituição'}</div><div style="margin-top:18px">${btn('Editar perfil','secondary','openProfileEdit()')}</div></aside><section class="card">${cardTitle('Visão geral','Um retrato do seu caminho recente.','🌱')}<div class="grid-4" style="margin-top:18px"><div class="stat"><div class="n">15</div><div class="label">dias de sequência</div></div><div class="stat"><div class="n">72%</div><div class="label">meta semanal</div></div><div class="stat"><div class="n">24</div><div class="label">sessões de foco</div></div><div class="stat"><div class="n">8</div><div class="label">conquistas</div></div></div><h3 style="margin-top:24px">Dados principais</h3><div class="list"><div class="row"><div><b>E-mail</b><div class="sub">${esc(state.data.user.email)}</div></div></div><div class="row"><div><b>Curso / turma</b><div class="sub">${esc(state.data.user.course)} · ${esc(state.data.user.class)}</div></div></div></div></section></div><section class="card" style="margin-top:20px">${cardTitle('Conquistas','Marcos leves para celebrar o que já aconteceu.')}<div class="grid-3" style="margin-top:16px">${[['🌱','Primeiros passos','Começou a registrar seus hábitos.'],['⏱️','Foco consistente','Concluiu 10 sessões Pomodoro.'],['💚','Momento Bloom','Registrou 7 dias de cuidado.']].map(x=>`<div class="achievement"><div class="medal">${x[0]}</div><div><b>${x[1]}</b><div class="sub">${x[2]}</div></div></div>`).join('')}</div></section>`)}
function openProfileEdit(){openModal('Editar perfil',`<div class="form-grid"><div class="field"><label>Nome</label><input id="pName" value="${esc(state.data.user.name)}"></div><div class="field"><label>E-mail</label><input id="pEmail" value="${esc(state.data.user.email)}"></div><div class="field"><label>Curso</label><input id="pCourse" value="${esc(state.data.user.course)}"></div><div class="field"><label>Turma</label><input id="pClass" value="${esc(state.data.user.class)}"></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveProfile()">Salvar</button></div>`)}
function saveProfile(){Object.assign(state.data.user,{name:$('#pName').value,email:$('#pEmail').value,course:$('#pCourse').value,class:$('#pClass').value});saveLocal();closeModal();render();toast('Perfil atualizado.')}

function settings(){return shell(pageHead('Preferências','Configurações','Personalize sua experiência e controle seus dados.')+`<div class="grid-2"><section class="card"><div class="eyebrow">Notificações</div>${settingSwitch('reminders','Tarefas e hábitos','Lembretes de rotina.')}${settingSwitch('study','Estudos','Sessões e planos.')}${settingSwitch('wellbeing','Bem-estar','Check-ins e práticas.')}${settingSwitch('institution','Instituição','Avisos e eventos.')}</section><section class="card"><div class="eyebrow">Aparência</div><div class="setting-row"><div><div class="setting-title">Tema</div><div class="setting-desc">Claro ou escuro.</div></div><button class="btn secondary" onclick="toggleTheme()">${state.theme==='light'?'Claro':'Escuro'}</button></div><div class="setting-row"><div><div class="setting-title">Cor de destaque</div><div class="setting-desc">Personalize a sensação visual do Bloom.</div></div><select onchange="toast('Cor de destaque atualizada.')"><option>Verde sage</option><option>Terracota</option><option>Pêssego</option></select></div><div class="setting-row"><div><div class="setting-title">Interface compacta</div><div class="setting-desc">Reduz espaços entre componentes.</div></div><button class="switch ${state.settings.compact?'on':''}" onclick="toggleSetting('compact')"><span></span></button></div></section></div><div class="grid-2" style="margin-top:20px"><section class="card"><div class="eyebrow">Home</div>${settingSwitch('homeMood','Mostrar check-in','Na Home.',true)}${settingSwitch('homeStudy','Mostrar estudo atual','Na Home.',true)}${settingSwitch('homeRecommendations','Mostrar recomendações','Na Home.',true)}</section><section class="card peach"><div class="eyebrow">Privacidade</div><h2 style="margin:8px 0">Seus dados pessoais ficam sob seu controle.</h2><p class="muted">Revise permissões, dados registrados e informações compartilhadas.</p><div class="head-actions">${btn('Política de privacidade','secondary','openPrivacy()')}${btn('Gerenciar dados','secondary','openDataPrivacy()')}</div></section></div><section class="card" style="margin-top:20px">${cardTitle('Conta','Ações de manutenção.')}<div class="head-actions" style="margin-top:15px">${linkBtn('Meu perfil','/perfil')}${btn('Exportar dados','secondary','exportData()')}${btn('Sair','danger','showToast(\'Logout demonstrativo.\')')}</div></section>`)}
function settingSwitch(key,title,desc,placeholder=false){if(placeholder&&!state.settings[key])state.settings[key]=true;return `<div class="setting-row"><div><div class="setting-title">${title}</div><div class="setting-desc">${desc}</div></div><button class="switch ${state.settings[key]?'on':''}" onclick="toggleSetting('${key}')"><span></span></button></div>`}
function toggleSetting(k){state.settings[k]=!state.settings[k];saveLocal();render();toast('Preferência atualizada.')}
function toggleTheme(){state.theme=state.theme==='light'?'dark':'light';localStorage.setItem('bloom-theme',state.theme);setTheme();render();toast('Tema atualizado.')}
function openPrivacy(){openModal('Privacidade',`<div class="list"><div class="row"><b>Dados pessoais</b><span>Nome, e-mail, curso</span></div><div class="row"><b>Dados emocionais</b><span>Check-ins e registros pessoais</span></div><div class="row"><b>Permissões</b><span>Localização somente para apoio, quando solicitada</span></div><div class="row"><b>Compartilhamento</b><span>Sem compartilhamento automático com a instituição</span></div></div><div class="modal-actions"><button class="btn primary" onclick="closeModal()">Fechar</button></div>`)}
function openDataPrivacy(){openModal('Gerenciar dados',`<p class="muted">Ações locais de demonstração para os dados do protótipo.</p><div class="head-actions">${btn('Exportar dados','secondary','exportData()')}${btn('Limpar dados locais','danger','clearLocalData()')}</div>`)}
function exportData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bloom-dados-demo.json';a.click();URL.revokeObjectURL(a.href);toast('Arquivo de demonstração preparado.')}
function clearLocalData(){localStorage.removeItem('bloom-data');location.reload()}

function openBreathing(){openModal('Respire no seu ritmo',`<div class="breath-modal"><div class="breath-orb">🌿</div><h3>Inspire devagar</h3><p class="muted">Inspire 4s · segure 2s · expire 6s.</p><button class="btn primary" onclick="toast('Exercício iniciado. Respire com calma.');closeModal()">Começar</button></div>`)}
function openSOS(){openModal('SOS',`<div class="card peach" style="box-shadow:none"><h3>Situação urgente?</h3><p class="muted">Neste protótipo, o SOS é apenas demonstrativo e não realiza chamadas reais.</p></div><div class="modal-actions"><button class="btn danger" onclick="toast('SOS demonstrativo acionado.');closeModal()">Acionar SOS</button><button class="btn secondary" onclick="closeModal()">Voltar</button></div>`)}
function openModal(title,body){$('#modal').innerHTML=`<div class="modal-head"><div><div class="eyebrow">Bloom</div><h2>${title}</h2></div><button class="modal-close" onclick="closeModal()">×</button></div>${body}`;$('#modalBackdrop').classList.add('open')}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function render(){
  setTheme();
  navbar();
  const p=route();
  const views={
    '/':home,'/organizar':organizar,'/organizar/tarefas':()=>{state.orgTab='Tarefas';return organizar()},'/organizar/calendario':()=>{state.orgTab='Calendário';return organizar()},'/organizar/habitos':()=>{state.orgTab='Hábitos';return organizar()},'/organizar/ideias':()=>{state.orgTab='Ideias';return organizar()},
    '/estudar':estudar,'/estudar/pomodoro':pomodoroPage,'/estudar/foco':focusPage,'/estudar/sons':soundsPage,'/estudar/progresso':progressPage,
    '/bem-estar':bemEstar,'/bem-estar/humor':()=>{state.wellTab='Humor';return bemEstar()},'/bem-estar/diario':()=>{state.wellTab='Diário';return bemEstar()},'/bem-estar/autoconhecimento':()=>{state.wellTab='Autoconhecimento';return bemEstar()},'/bem-estar/respiracao':()=>{state.wellTab='Respiração';return bemEstar()},'/bem-estar/apoio':()=>{state.wellTab='Apoio';return bemEstar()},
    '/instituicao':instituicao,'/instituicao/eventos':()=>{state.instTab='Eventos e campanhas';return instituicao()},'/instituicao/comunicados':()=>{state.instTab='Comunicação';return instituicao()},'/instituicao/servicos':()=>{state.instTab='Apoio';return instituicao()},'/instituicao/comunidades':()=>{state.instTab='Comunidades';return instituicao()},
    '/notificacoes':notifications,'/perfil':profile,'/configuracoes':settings
  };
  $('#app').innerHTML=(views[p]||home)();
  window.scrollTo({top:0,behavior:'instant'});
}

window.addEventListener('hashchange',render);
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.addEventListener('click',e=>{if(e.target=== $('#modalBackdrop'))closeModal()});
$('#notificationButton').addEventListener('click',()=>go('/notificacoes'));
$('#profileMenu').addEventListener('click',()=>openModal('Conta rápida',`<div class="list"><a class="row" href="#/perfil" onclick="closeModal()"><div class="left"><div class="mini-icon">👤</div><div><b>Meu perfil</b><div class="sub">Dados, conquistas e atividade</div></div></div><span>→</span></a><a class="row" href="#/configuracoes" onclick="closeModal()"><div class="left"><div class="mini-icon">⚙️</div><div><b>Configurações</b><div class="sub">Preferências e privacidade</div></div></div><span>→</span></a></div>`));
render();
