(()=>{
 const launcher=()=>document.querySelector('#bloomMascot');
 if(launcher()) return;
 document.body.insertAdjacentHTML('beforeend',`<button id="bloomMascot" class="bloom-mascot" aria-label="Abrir Assistente Bloom"><span class="capy-head"><i></i><i></i><b></b></span><span class="capy-leaf"></span></button><aside id="bloomChat" class="bloom-chat" aria-label="Assistente Bloom"><header><div class="chat-avatar">🌿</div><div><b>Assistente Bloom</b><small>Um apoio rápido para o seu próximo passo.</small></div><button class="chat-close" id="chatClose" aria-label="Fechar">×</button></header><div class="chat-body" id="chatBody"><div class="chat-msg bot">Oi, Ana. Eu posso ajudar você a organizar o dia, estudar, fazer uma pausa ou encontrar apoio.</div><div class="chat-quick"><button data-chat="organizar">Organizar</button><button data-chat="estudar">Estudar</button><button data-chat="pausa">Fazer uma pausa</button><button data-chat="apoio">Encontrar apoio</button></div></div><form id="chatForm"><input id="chatInput" placeholder="Escreva uma mensagem…" autocomplete="off"><button>Enviar</button></form></aside>`);
 const mascot=()=>document.querySelector('#bloomMascot'),chat=()=>document.querySelector('#bloomChat');
 const input=()=>document.querySelector('#chatInput'),body=()=>document.querySelector('#chatBody');
 mascot().addEventListener('click',()=>{chat().classList.toggle('open');if(chat().classList.contains('open'))input().focus();});
 document.querySelector('#chatClose').addEventListener('click',()=>chat().classList.remove('open'));
 const reply=(text,user=false)=>{const d=document.createElement('div');d.className='chat-msg '+(user?'user':'bot');d.textContent=text;body().appendChild(d);body().scrollTop=body().scrollHeight;};
 const respond=t=>{t=t.toLowerCase();if(t.includes('organ'))return'Vamos por partes. Abra Organizar e escolha apenas a próxima tarefa.';if(t.includes('estud')||t.includes('foco')||t.includes('pomodoro'))return'Você pode abrir Estudar e começar um Pomodoro curto. Depois faça uma pausa.';if(t.includes('pausa')||t.includes('respir')||t.includes('cans'))return'Uma pausa de um minuto pode ser suficiente agora. Abra Bem-estar → Práticas.';if(t.includes('apoio')||t.includes('ajuda'))return'Abra Bem-estar → Apoio ou solicite acolhimento dentro de Instituição.';if(t.includes('notifica'))return'As notificações são centralizadas em Notificações e controladas por categoria em Configurações.';return'Posso ajudar com Organizar, Estudar, Bem-estar, Instituição e notificações. O que você precisa agora?';};
 document.querySelector('#chatForm').addEventListener('submit',e=>{e.preventDefault();const t=input().value.trim();if(!t)return;reply(t,true);input().value='';setTimeout(()=>reply(respond(t)),220);});
 document.querySelector('.chat-quick').addEventListener('click',e=>{const b=e.target.closest('[data-chat]');if(!b)return;reply(b.textContent,true);setTimeout(()=>reply(respond(b.dataset.chat)),180);});
})();